apiVersion: v1
kind: ServiceAccount
metadata:
  name: pharma-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pharma-secret-reader
automountServiceAccountToken: false
