apiVersion: v1
kind: Service
metadata:
  name: pharma-api
  labels:
    app.kubernetes.io/name: pharma-api
    app.kubernetes.io/part-of: pharma-intelligence
spec:
  selector:
    app.kubernetes.io/name: pharma-api
  ports:
    - name: http
      port: 8080
      targetPort: http
