export const appliedFilterLabels = {
  q: "关键词",
  modality: "药物类型",
  innovation_type: "创新类型",
  therapeutic_area: "适应症领域",
  drug_category: "药品类别",
  program_status: "项目状态",
  organization_role: "机构角色",
  organization_type: "机构类型",
  organization_country_region: "机构所在地区",
  phase: "总体最高阶段",
  geography: "记录地区",
  status_date_from: "状态日期",
  status_date_to: "状态日期",
  drug_entity_id: "药品",
  target_entity_id: "靶点",
  target_combination_key: "靶点组合",
  disease_entity_id: "适应症",
  organization_entity_id: "研发机构",
  global_phase: "全球最高阶段",
  china_phase: "中国最高阶段",
  global_phase_started_from: "全球阶段起始",
  global_phase_started_to: "全球阶段起始",
  china_phase_started_from: "中国阶段起始",
  china_phase_started_to: "中国阶段起始",
  development_rights_region: "研发权益地区",
  commercialization_rights_region: "商业化权益地区",
  program_tag: "项目标签",
  milestone_type: "里程碑类型",
  milestone_from: "里程碑日期",
  milestone_to: "里程碑日期",
  has_clinical_results: "临床结果",
  clinical_result_evaluation: "结果评价",
  has_deal: "交易记录",
  deal_currency: "交易币种",
  deal_total_potential_amount_min: "潜在总额",
  deal_total_potential_amount_max: "潜在总额",
} as const;

export const programStatusLabels: Record<string, string> = {
  active: "进行中",
  inactive: "已停止",
  unknown: "状态未披露",
};
