import { contractRequest } from "../contract";
import { type ExportFormat, exportPayloadToBlob } from "../download";
import type { WorkspaceDomainExportCreate } from "../generated";
import { WorkspaceExportsService } from "../generated";

export type DomainExportDataset = WorkspaceDomainExportCreate["dataset"];
export type DomainExportField = { value: string; label: string };

export const domainExportCatalog: Record<
  DomainExportDataset,
  { label: string; fields: DomainExportField[]; queryFields: string[] }
> = {
  entities: {
    label: "实体检索",
    fields: [
      { value: "id", label: "稳定 ID" },
      { value: "entity_type", label: "实体类型" },
      { value: "name", label: "名称" },
      { value: "description", label: "描述" },
      { value: "external_ids", label: "外部标识" },
      { value: "review_status", label: "数据状态" },
      { value: "updated_at", label: "更新时间" },
    ],
    queryFields: ["q", "entity_type", "entity_types", "review_status", "sort", "sort_by", "sort_direction"],
  },
  pipelines: {
    label: "药物与管线",
    fields: [
      { value: "id", label: "稳定 ID" },
      { value: "drug_name", label: "药物" },
      { value: "target_name", label: "靶点" },
      { value: "disease_name", label: "适应症" },
      { value: "organization_name", label: "研发机构" },
      { value: "organizations", label: "机构角色与权益关系" },
      { value: "modality", label: "模态" },
      { value: "innovation_type", label: "创新类型" },
      { value: "therapeutic_area", label: "适应症领域" },
      { value: "drug_category", label: "药品类别" },
      { value: "program_status", label: "项目状态" },
      { value: "mechanism_of_action", label: "作用机制" },
      { value: "global_phase", label: "全球阶段" },
      { value: "china_phase", label: "中国阶段" },
      { value: "status_date", label: "状态日期" },
      { value: "development_rights_regions", label: "开发权益" },
      { value: "commercialization_rights_regions", label: "商业化权益" },
      { value: "clinical_trial_count", label: "临床试验数" },
      { value: "has_clinical_results", label: "是否已有临床结果" },
      { value: "clinical_result_evaluations", label: "临床结果评价" },
      { value: "deal_count", label: "交易数" },
      { value: "deal_currencies", label: "交易币种" },
      { value: "source_document_id", label: "来源文档" },
    ],
    queryFields: [
      "q",
      "modality",
      "innovation_type",
      "therapeutic_area",
      "drug_category",
      "program_status",
      "organization_role",
      "organization_type",
      "organization_country_region",
      "phase",
      "geography",
      "status_date_from",
      "status_date_to",
      "drug_entity_id",
      "target_entity_id",
      "target_combination_key",
      "disease_entity_id",
      "organization_entity_id",
      "global_phase",
      "china_phase",
      "global_phase_started_from",
      "global_phase_started_to",
      "china_phase_started_from",
      "china_phase_started_to",
      "development_rights_region",
      "commercialization_rights_region",
      "program_tag",
      "milestone_type",
      "milestone_from",
      "milestone_to",
      "has_clinical_results",
      "clinical_result_evaluation",
      "has_deal",
      "deal_currency",
      "deal_total_potential_amount_min",
      "deal_total_potential_amount_max",
      "sort",
      "sort_by",
      "sort_direction",
    ],
  },
  trials: {
    label: "临床试验",
    fields: [
      { value: "id", label: "稳定 ID" },
      { value: "registry_name", label: "注册平台" },
      { value: "registry_id", label: "注册号" },
      { value: "official_title", label: "试验标题" },
      { value: "overall_status", label: "试验状态" },
      { value: "phases", label: "临床分期" },
      { value: "study_type", label: "研究类型" },
      { value: "enrollment", label: "入组人数" },
      { value: "has_results", label: "结果发布" },
      { value: "result_evaluation", label: "结果评价" },
      { value: "last_update_posted", label: "最近更新" },
      { value: "source_document_id", label: "来源文档" },
    ],
    queryFields: [
      "q",
      "registry",
      "status",
      "phase",
      "study_type",
      "acronym",
      "initiation_type",
      "therapy_line",
      "has_results",
      "result_evaluation",
      "results_posted_from",
      "results_posted_to",
      "investigational_drug",
      "combination_drug",
      "investigational_target",
      "combination_target",
      "investigational_drug_entity_ids",
      "combination_drug_entity_ids",
      "investigational_target_entity_ids",
      "combination_target_entity_ids",
      "linked_drug_modality",
      "linked_drug_innovation_type",
      "linked_drug_category",
      "linked_drug_program_tag",
      "linked_drug_global_phase",
      "linked_drug_organization_country_region",
      "role_entity_id",
      "role_entity_ids",
      "role_entity_role",
      "has_key_result",
      "publication_id",
      "conference",
      "disclosed_from",
      "disclosed_to",
      "sort",
      "sort_by",
      "sort_direction",
    ],
  },
  patents: {
    label: "专利情报",
    fields: [
      { value: "id", label: "稳定 ID" },
      { value: "family_identifier", label: "专利族" },
      { value: "title", label: "标题" },
      { value: "priority_date", label: "最早优先权" },
      { value: "applicants", label: "申请人" },
      { value: "legal_status", label: "法律状态" },
      { value: "expiration_date", label: "预计到期" },
      { value: "linked_entities", label: "关联实体" },
      { value: "source_document_id", label: "来源文档" },
    ],
    queryFields: [
      "q",
      "entity_id",
      "applicant",
      "legal_status",
      "priority_from",
      "priority_to",
      "expiration_from",
      "expiration_to",
      "sort",
      "sort_by",
      "sort_direction",
    ],
  },
  deals: {
    label: "交易情报",
    fields: [
      { value: "id", label: "稳定 ID" },
      { value: "name", label: "交易名称" },
      { value: "deal_type", label: "交易类型" },
      { value: "status", label: "交易状态" },
      { value: "direction", label: "交易方向" },
      { value: "announced_at", label: "披露日期" },
      { value: "parties", label: "参与方" },
      { value: "territory", label: "权益地区" },
      { value: "upfront_amount", label: "首付款" },
      { value: "total_potential_amount", label: "潜在总额" },
      { value: "currency", label: "币种" },
      { value: "source_document_id", label: "来源文档" },
    ],
    queryFields: [
      "q",
      "deal_type",
      "status",
      "direction",
      "direction_reference_jurisdiction",
      "territory",
      "asset_entity_id",
      "target_entity_id",
      "disease_entity_id",
      "asset_modality",
      "asset_program_tag",
      "party",
      "party_entity_id",
      "party_role",
      "party_country_region",
      "party_organization_type",
      "development_phase_at_transaction",
      "current_development_phase",
      "right_type",
      "rights_territory",
      "currency",
      "announced_from",
      "announced_to",
      "terminated_from",
      "terminated_to",
      "source_updated_from",
      "source_updated_to",
      "upfront_amount_min",
      "upfront_amount_max",
      "total_potential_amount_min",
      "total_potential_amount_max",
      "sort",
      "sort_by",
      "sort_direction",
    ],
  },
  regulatory: {
    label: "监管与安全",
    fields: [
      { value: "id", label: "稳定 ID" },
      { value: "title", label: "事件标题" },
      { value: "agency", label: "监管机构" },
      { value: "jurisdiction", label: "司法辖区" },
      { value: "event_type", label: "事件类型" },
      { value: "status", label: "状态" },
      { value: "decision_date", label: "决定日期" },
      { value: "designation_type", label: "认定资格" },
      { value: "label_change_type", label: "标签变更" },
      { value: "safety_signal_type", label: "安全信号" },
      { value: "source_document_id", label: "来源文档" },
    ],
    queryFields: [
      "q",
      "agency",
      "jurisdiction",
      "event_type",
      "status",
      "designation_type",
      "label_change_type",
      "has_boxed_warning",
      "safety_signal_type",
      "safety_severity",
      "safety_status",
      "decision_from",
      "decision_to",
      "source_updated_from",
      "source_updated_to",
      "sort",
      "sort_by",
      "sort_direction",
    ],
  },
  epidemiology: {
    label: "流行病学",
    fields: [
      { value: "id", label: "稳定 ID" },
      { value: "observation_identifier", label: "观察编号" },
      { value: "disease_entity", label: "疾病" },
      { value: "measure", label: "指标" },
      { value: "value", label: "估计值" },
      { value: "lower_bound", label: "下界" },
      { value: "upper_bound", label: "上界" },
      { value: "unit", label: "单位" },
      { value: "geography", label: "地区" },
      { value: "population_scope", label: "人群口径" },
      { value: "period_start", label: "观察期起" },
      { value: "period_end", label: "观察期止" },
      { value: "source_document_id", label: "来源文档" },
    ],
    queryFields: [
      "q",
      "disease_entity_id",
      "measure",
      "geography",
      "unit",
      "population_scope",
      "patient_population_id",
      "age_group",
      "sex",
      "period_start_from",
      "period_end_to",
      "sort",
      "sort_by",
      "sort_direction",
    ],
  },
  news: {
    label: "新闻与研究事件",
    fields: [
      { value: "id", label: "稳定 ID" },
      { value: "event_type", label: "事件类型" },
      { value: "title", label: "标题" },
      { value: "summary", label: "摘要" },
      { value: "published_at", label: "发布日期" },
      { value: "language", label: "语言" },
      { value: "publisher_entity", label: "发布方" },
      { value: "canonical_url", label: "原始页面" },
      { value: "venue", label: "会议或期刊" },
      { value: "source_document_id", label: "来源文档" },
    ],
    queryFields: [
      "q",
      "entity_id",
      "event_type",
      "publisher",
      "language",
      "venue",
      "content_scope",
      "published_from",
      "published_to",
      "sort",
      "sort_by",
      "sort_direction",
    ],
  },
};

export const defaultWorkspacePolicyFields = Object.entries(domainExportCatalog).flatMap(([dataset, config]) =>
  config.fields.map((field) => `${dataset}.${field.value}`),
);

const exportEntityTypes = new Set([
  "drug",
  "target",
  "disease",
  "organization",
  "clinical_trial",
  "patent",
  "transaction",
  "product",
  "technology",
  "person",
]);
const repeatedDomainQueryFields = new Set([
  "sort",
  "role_entity_ids",
  "investigational_drug_entity_ids",
  "combination_drug_entity_ids",
  "investigational_target_entity_ids",
  "combination_target_entity_ids",
  "linked_drug_modality",
  "linked_drug_innovation_type",
  "linked_drug_category",
  "linked_drug_program_tag",
  "asset_modality",
  "asset_program_tag",
  "modality",
  "innovation_type",
  "therapeutic_area",
  "drug_category",
  "program_tag",
]);

export function currentDomainExportQuery(dataset: DomainExportDataset): Record<string, string | string[]> {
  const params = new URLSearchParams(window.location.search);
  const query: Record<string, string | string[]> = Object.fromEntries(
    domainExportCatalog[dataset].queryFields.flatMap((field) => {
      if (dataset === "entities" && (field === "entity_type" || field === "entity_types")) return [];
      const values = Array.from(new Set(params.getAll(field).filter(Boolean))).slice(0, 20);
      if (!values.length) return [];
      return [[field, repeatedDomainQueryFields.has(field) || values.length > 1 ? values : (values[0] ?? "")]];
    }),
  );
  if (dataset === "entities") {
    // The research workspace always searches published entities, even when an
    // obsolete URL contains a draft status. Carry that same boundary to export.
    query.review_status = "verified";
    const selectedTypes = Array.from(
      new Set(
        (params.get("types") ?? "")
          .split(",")
          .map((value) => value.trim())
          .filter((value) => exportEntityTypes.has(value)),
      ),
    ).slice(0, 10);
    const legacyType = params.get("type") ?? params.get("entity_type") ?? "";
    if (selectedTypes.length > 1) query.entity_types = selectedTypes;
    else if (selectedTypes.length === 1) query.entity_type = selectedTypes[0] ?? "";
    else if (exportEntityTypes.has(legacyType)) query.entity_type = legacyType;
  }
  return query;
}

export async function exportDomainQuery(requestBody: WorkspaceDomainExportCreate): Promise<Blob> {
  const payload = await contractRequest(
    WorkspaceExportsService.exportWorkspaceDomainQueryApiV1WorkspaceDomainExportsPost({ requestBody }),
  );
  return exportPayloadToBlob(payload, requestBody.export_format as ExportFormat);
}
