import type {
  BillingAccountRead,
  BillingDeliveryRead,
  BillingDisputeRead,
  CommercialClientRead,
  CommercialOverviewRead,
  CommercialRiskEventRead,
  DataExportRead,
  DataLifecycleEventRead,
  LegalHoldRead,
} from "../src/lib/generated";
import { controlledCommercialClient } from "./commercial-fixture";

const time = "2026-10-10T00:00:00Z";
export const recordClient: CommercialClientRead = {
  ...controlledCommercialClient,
  subjects: [{ actor_type: "service", subject_id: "Original inactive subject <source>", active: false }],
};
export const recordOverview: CommercialOverviewRead = {
  as_of: time,
  period_start: time,
  active_client_count: 1,
  open_risk_count: 0,
  subscriptions: [
    {
      subscription_id: "controlled-subscription",
      subscription_key: "ORIGINAL_SUBSCRIPTION",
      client_key: recordClient.client_key,
      client_name: recordClient.display_name,
      billing_account_key: "ORIGINAL_ACCOUNT",
      billing_account_name: "Original account <source>",
      status: "active",
      starts_at: time,
      ends_at: null,
      rate_card_key: "ORIGINAL_RATE",
      rate_card_revision: 2,
      granted_units: "1.000000001",
      consumed_units: "0.000000001",
      reserved_units: "0",
      available_units: "1",
      active_reservations: 0,
      daily_unique_records: 0,
      daily_usage: {
        new_unique_record_count: 0,
        unique_record_count: 0,
        response_bytes: 0,
        result_count: 0,
        settlement_count: 0,
      },
      entitlements: [
        {
          key: "ORIGINAL_ENTITLEMENT",
          data_domains: ["original_domain"],
          daily_unit_limit: "0.000000001",
          daily_unique_record_limit: null,
          max_page_depth: 5,
          max_response_bytes: 1024,
          max_result_rows: 25,
        },
      ],
    },
  ],
};
export const recordAccount: BillingAccountRead = {
  id: "controlled-account",
  account_key: "ORIGINAL_ACCOUNT",
  display_name: "Original account <source>",
  currency: "USD",
  status: "active",
  external_customer_reference_masked: "CONTROLLED_MASKED_REFERENCE",
  mapping_configured: true,
  invoice_count: 1,
  statement_count: 1,
  unresolved_statement_count: 0,
  updated_at: time,
};
export const recordDelivery: BillingDeliveryRead = {
  event_id: "controlled-delivery-event",
  delivery_id: "controlled-delivery",
  statement_id: "controlled-statement",
  statement_key: "ORIGINAL_STATEMENT",
  billing_account_id: recordAccount.id,
  billing_account_key: recordAccount.account_key,
  billing_account_name: recordAccount.display_name,
  attempts: 1,
  state: "succeeded",
  available_at: time,
  processed_at: time,
  created_at: time,
  lease_expires_at: null,
  external_invoice_id: "ORIGINAL_INVOICE",
  invoice_provider: "ORIGINAL_PROVIDER",
  invoice_status: "paid",
  last_error: "Original provider detail <source>",
};
export const recordDispute: BillingDisputeRead = {
  id: "controlled-dispute",
  dispute_key: "ORIGINAL_DISPUTE",
  subject: "Original dispute <source>",
  description: "Original dispute description <source>",
  billing_account_id: recordAccount.id,
  billing_account_key: recordAccount.account_key,
  billing_account_name: recordAccount.display_name,
  statement_id: recordDelivery.statement_id,
  statement_key: recordDelivery.statement_key,
  subscription_id: recordOverview.subscriptions[0].subscription_id,
  category: "usage",
  status: "resolved",
  disputed_units: "0.000000001",
  due_at: time,
  assigned_to: "ORIGINAL_ASSIGNEE",
  overdue: false,
  created_at: time,
  updated_at: time,
  opened_at: time,
  opened_by: "ORIGINAL_OPERATOR",
  resolved_at: time,
  resolved_by: "ORIGINAL_REVIEWER",
  resolution_code: "ORIGINAL_CODE",
  resolution_notes: "Original resolution <source>",
  resolution_adjustment_key: "ORIGINAL_ADJUSTMENT",
  invoice_reference_id: null,
  external_invoice_id: recordDelivery.external_invoice_id,
  version: 3,
};
export const recordExport: DataExportRead = {
  id: "controlled-export",
  dataset: "original_dataset",
  format: "jsonl",
  state: "succeeded",
  fields: ["original.field"],
  filters: { original_filter: "Original filter <source>" },
  max_records: 25,
  record_count: 0,
  artifact_bytes: 0,
  artifact_sha256: "a".repeat(64),
  license_attribution: "Original license <source>",
  license_policy_version: "ORIGINAL_POLICY",
  license_policy_sha256: "b".repeat(64),
  manifest_key_id: "ORIGINAL_KEY_ID",
  manifest_sha256: "c".repeat(64),
  manifest_signature: "CONTROLLED_SIGNATURE",
  requested_at: time,
  started_at: time,
  completed_at: time,
  expires_at: time,
  approved_at: time,
  approved_by: "ORIGINAL_APPROVER",
  approval_required: true,
  failure_code: null,
  failure_message: "Original failure detail <source>",
};
export const recordRisk: CommercialRiskEventRead = {
  id: "controlled-risk",
  actor_type: "service",
  subject_id: "ORIGINAL_SUBJECT",
  client_id: recordClient.id,
  client_key: recordClient.client_key,
  client_name: recordClient.display_name,
  case_status: "resolved",
  case_notes: "Original review <source>",
  details: { original_detail: "Original risk detail <source>" },
  entitlement_key: "ORIGINAL_ENTITLEMENT",
  existing_unique_records: 0,
  projected_unique_records: 1,
  requested_records: 1,
  page_depth: 1,
  phase: "ORIGINAL_PHASE",
  occurred_at: time,
  reviewed_at: time,
  reviewed_by: "ORIGINAL_REVIEWER",
  query_sha256: "d".repeat(64),
  reason_code: "ORIGINAL_REASON",
  request_id: "ORIGINAL_REQUEST",
};
export const recordHold: LegalHoldRead = {
  id: "controlled-hold",
  matter_reference: "ORIGINAL_MATTER",
  scope_type: "tenant",
  scope_id: null,
  status: "released",
  reason: "Original hold reason <source>",
  placed_at: time,
  placed_by_user_id: "ORIGINAL_OPERATOR",
  released_at: time,
  released_by_user_id: "ORIGINAL_REVIEWER",
  release_reason: "Original release <source>",
};
export const recordEvent: DataLifecycleEventRead = {
  id: "controlled-lifecycle-event",
  target_id: recordExport.id,
  target_type: "export_artifact",
  action: "blocked",
  outcome: "blocked",
  actor_user_id: "ORIGINAL_OPERATOR",
  data_class: "commercial_export_artifact",
  idempotency_key: "ORIGINAL_OPERATION_KEY",
  policy_id: "controlled-policy",
  policy_version: 2,
  legal_hold_ids: [recordHold.id],
  reason: "Original lifecycle reason <source>",
  created_at: time,
  details: { original_dependency: "Original audit detail <source>" },
};
