import type { savedSearchMessages } from "../../lib/i18n/savedSearch";

export type SavedSearchConditionKind = "text" | "date" | "boolean" | "entity" | "list" | "enum";
export type SavedSearchConditionField = {
  key: string;
  label: keyof typeof savedSearchMessages;
  kind?: SavedSearchConditionKind;
};

const commonFields: readonly SavedSearchConditionField[] = [
  { key: "sort", label: "多字段排序", kind: "list" },
  { key: "sort_by", label: "排序字段", kind: "text" },
  { key: "sort_direction", label: "排序方向" },
];
const domainFields: Record<string, readonly SavedSearchConditionField[]> = {
  entity_search: [
    { key: "review_status", label: "数据状态" },
    { key: "include_related", label: "关联检索", kind: "boolean" },
  ],
  pipeline_search: [
    { key: "target_entity_id", label: "靶点", kind: "entity" },
    { key: "target_combination_key", label: "靶点组合", kind: "entity" },
    { key: "disease_entity_id", label: "适应症", kind: "entity" },
    { key: "organization_entity_id", label: "研发机构", kind: "entity" },
    { key: "modality", label: "模态", kind: "list" },
    { key: "drug_category", label: "药品类别", kind: "list" },
    { key: "innovation_type", label: "创新类型", kind: "list" },
    { key: "program_tag", label: "项目标签", kind: "list" },
    { key: "phase", label: "最高阶段" },
    { key: "global_phase", label: "全球阶段" },
    { key: "china_phase", label: "中国阶段" },
    { key: "program_status", label: "项目状态" },
    { key: "organization_role", label: "机构角色" },
    { key: "organization_type", label: "机构类型" },
    { key: "organization_country_region", label: "机构所在地区", kind: "text" },
    { key: "development_rights_region", label: "研发权益地区", kind: "text" },
    { key: "commercialization_rights_region", label: "商业化权益地区", kind: "text" },
    { key: "analysis_dimension", label: "分析维度" },
    { key: "analysis_limit", label: "分析范围" },
    { key: "analysis_stage_scope", label: "阶段口径" },
    { key: "target_aggregation", label: "靶点聚合" },
    { key: "has_clinical_results", label: "临床结果", kind: "boolean" },
    { key: "has_deal", label: "交易记录", kind: "boolean" },
    { key: "global_phase_started_from", label: "全球阶段起始", kind: "date" },
    { key: "global_phase_started_to", label: "全球阶段截止", kind: "date" },
    { key: "drug_entity_id", label: "药物实体", kind: "entity" },
    { key: "clinical_result_evaluation", label: "临床结果评价" },
    { key: "geography", label: "项目地区", kind: "text" },
    { key: "milestone_from", label: "里程碑日期起", kind: "date" },
    { key: "milestone_to", label: "里程碑日期止", kind: "date" },
    { key: "milestone_type", label: "里程碑类型" },
    { key: "therapeutic_area", label: "治疗领域", kind: "list" },
    { key: "status_date_from", label: "状态日期起", kind: "date" },
    { key: "status_date_to", label: "状态日期止", kind: "date" },
    { key: "china_phase_started_from", label: "中国阶段起始", kind: "date" },
    { key: "china_phase_started_to", label: "中国阶段截止", kind: "date" },
    { key: "deal_currency", label: "交易币种", kind: "text" },
    { key: "deal_total_potential_amount_min", label: "潜在交易总额下界" },
    { key: "deal_total_potential_amount_max", label: "潜在交易总额上界" },
  ],
  clinical_trial_search: [
    { key: "registry", label: "注册平台", kind: "text" },
    { key: "status", label: "试验状态" },
    { key: "phase", label: "临床分期" },
    { key: "study_type", label: "研究类型" },
    { key: "acronym", label: "试验简称", kind: "text" },
    { key: "initiation_type", label: "发起类型" },
    { key: "therapy_line", label: "治疗线次" },
    { key: "has_results", label: "结果披露", kind: "boolean" },
    { key: "result_evaluation", label: "结果评价" },
    { key: "investigational_drug_entity_ids", label: "试验药物", kind: "entity" },
    { key: "combination_drug_entity_ids", label: "联用药物", kind: "entity" },
    { key: "investigational_target_entity_ids", label: "试验靶点", kind: "entity" },
    { key: "combination_target_entity_ids", label: "联用靶点", kind: "entity" },
    { key: "publication_id", label: "发表编号", kind: "text" },
    { key: "conference", label: "会议", kind: "text" },
    { key: "results_posted_from", label: "结果发布日期起", kind: "date" },
    { key: "results_posted_to", label: "结果发布日期止", kind: "date" },
    { key: "investigational_drug", label: "试验药物名称", kind: "text" },
    { key: "combination_drug", label: "联用药物名称", kind: "text" },
    { key: "investigational_target", label: "试验靶点名称", kind: "text" },
    { key: "combination_target", label: "联用靶点名称", kind: "text" },
    { key: "disclosed_from", label: "披露日期起", kind: "date" },
    { key: "disclosed_to", label: "披露日期止", kind: "date" },
    { key: "has_key_result", label: "关键结果", kind: "boolean" },
    { key: "role_entity_id", label: "登记角色实体", kind: "entity" },
    { key: "role_entity_ids", label: "登记角色实体", kind: "entity" },
    { key: "role_entity_role", label: "登记实体角色" },
    { key: "linked_drug_category", label: "关联药物类别", kind: "list" },
    { key: "linked_drug_global_phase", label: "关联药物全球阶段" },
    { key: "linked_drug_innovation_type", label: "关联药物创新类型", kind: "list" },
    { key: "linked_drug_modality", label: "关联药物模态", kind: "list" },
    { key: "linked_drug_organization_country_region", label: "关联药物机构地区", kind: "text" },
    { key: "linked_drug_program_tag", label: "关联药物项目标签", kind: "list" },
  ],
  patent_search: [
    { key: "applicant", label: "申请人", kind: "text" },
    { key: "legal_status", label: "法律状态" },
    { key: "entity_id", label: "关联实体", kind: "entity" },
    { key: "priority_from", label: "优先权日起", kind: "date" },
    { key: "priority_to", label: "优先权日止", kind: "date" },
    { key: "expiration_from", label: "到期日起", kind: "date" },
    { key: "expiration_to", label: "到期日止", kind: "date" },
  ],
  deal_search: [
    { key: "deal_type", label: "交易类型" },
    { key: "status", label: "交易状态" },
    { key: "direction", label: "交易方向" },
    { key: "territory", label: "权益地区", kind: "text" },
    { key: "party", label: "参与机构", kind: "text" },
    { key: "party_entity_id", label: "参与机构实体", kind: "entity" },
    { key: "party_role", label: "参与角色" },
    { key: "asset_entity_id", label: "交易资产", kind: "entity" },
    { key: "asset_modality", label: "资产模态", kind: "list" },
    { key: "development_phase_at_transaction", label: "交易时阶段" },
    { key: "current_development_phase", label: "当前最高阶段" },
    { key: "right_type", label: "权益类型" },
    { key: "currency", label: "币种", kind: "text" },
    { key: "announced_from", label: "初始披露日起", kind: "date" },
    { key: "announced_to", label: "初始披露日止", kind: "date" },
    { key: "asset_program_tag", label: "资产项目标签", kind: "list" },
    { key: "direction_reference_jurisdiction", label: "交易方向参考辖区", kind: "text" },
    { key: "disease_entity_id", label: "适应症", kind: "entity" },
    { key: "party_country_region", label: "参与机构地区", kind: "text" },
    { key: "party_organization_type", label: "参与机构类型", kind: "text" },
    { key: "rights_territory", label: "具体权益地区", kind: "text" },
    { key: "source_updated_from", label: "来源更新日起", kind: "date" },
    { key: "source_updated_to", label: "来源更新日止", kind: "date" },
    { key: "target_entity_id", label: "靶点", kind: "entity" },
    { key: "terminated_from", label: "终止日起", kind: "date" },
    { key: "terminated_to", label: "终止日止", kind: "date" },
    { key: "total_potential_amount_min", label: "潜在总额下界" },
    { key: "total_potential_amount_max", label: "潜在总额上界" },
    { key: "upfront_amount_min", label: "首付款下界" },
    { key: "upfront_amount_max", label: "首付款上界" },
    { key: "analysis_dimension", label: "分析维度" },
    { key: "analysis_limit", label: "分析范围" },
  ],
  regulatory_search: [
    { key: "agency", label: "监管机构", kind: "text" },
    { key: "jurisdiction", label: "辖区", kind: "text" },
    { key: "event_type", label: "事件类型" },
    { key: "status", label: "事件状态" },
    { key: "designation_type", label: "认定资格" },
    { key: "label_change_type", label: "标签变更" },
    { key: "safety_signal_type", label: "安全信号" },
    { key: "safety_severity", label: "严重程度" },
    { key: "safety_status", label: "信号状态" },
    { key: "has_boxed_warning", label: "黑框警告", kind: "boolean" },
    { key: "decision_from", label: "决定日起", kind: "date" },
    { key: "decision_to", label: "决定日止", kind: "date" },
    { key: "source_updated_from", label: "来源更新日起", kind: "date" },
    { key: "source_updated_to", label: "来源更新日止", kind: "date" },
  ],
  epidemiology_search: [
    { key: "disease_entity_id", label: "疾病", kind: "entity" },
    { key: "patient_population_id", label: "患者人群", kind: "entity" },
    { key: "measure", label: "指标" },
    { key: "geography", label: "地区", kind: "text" },
    { key: "population_scope", label: "人群口径", kind: "text" },
    { key: "age_group", label: "年龄", kind: "text" },
    { key: "sex", label: "性别", kind: "text" },
    { key: "unit", label: "单位", kind: "text" },
    { key: "period_start_from", label: "观测期起", kind: "date" },
    { key: "period_end_to", label: "观测期止", kind: "date" },
  ],
  news_search: [
    { key: "event_type", label: "事件类型" },
    { key: "publisher", label: "发布方", kind: "text" },
    { key: "venue", label: "会议/期刊", kind: "text" },
    { key: "language", label: "语言", kind: "text" },
    { key: "content_scope", label: "研究范围", kind: "text" },
    { key: "entity_id", label: "关联实体", kind: "entity" },
    { key: "published_from", label: "发布日期起", kind: "date" },
    { key: "published_to", label: "发布日期止", kind: "date" },
  ],
};

export const savedSearchConditionFields: Record<string, readonly SavedSearchConditionField[]> = Object.fromEntries(
  Object.entries(domainFields).map(([kind, fields]) => [kind, [...fields, ...commonFields]]),
);
