"""add commercial mcp ledger

Revision ID: 1dd8b6ad33c4
Revises: c74e8c9f132d
Create Date: 2026-07-16 00:52:20.029975

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1dd8b6ad33c4"
down_revision: str | Sequence[str] | None = "c74e8c9f132d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "agent_clients",
    "agent_client_subjects",
    "billing_accounts",
    "rate_card_versions",
    "rate_card_items",
    "commercial_subscriptions",
    "commercial_entitlements",
    "credit_grants",
    "usage_reservations",
    "usage_events",
    "usage_settlements",
    "commercial_ledger_entries",
    "billing_adjustments",
    "invoice_references",
)

IMMUTABLE_TABLES = (
    "rate_card_versions",
    "rate_card_items",
    "credit_grants",
    "usage_events",
    "usage_settlements",
    "commercial_ledger_entries",
    "billing_adjustments",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('client_key', sa.String(length=120), nullable=False),
    sa.Column('oauth_client_id', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'client_key'),
    sa.UniqueConstraint('tenant_id', 'oauth_client_id')
    )
    op.create_index(op.f('ix_agent_clients_active'), 'agent_clients', ['active'], unique=False)
    op.create_index(op.f('ix_agent_clients_tenant_id'), 'agent_clients', ['tenant_id'], unique=False)
    op.create_table('billing_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('account_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='billingaccountstatus'), nullable=False),
    sa.Column('external_customer_reference', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(currency) = 3', name='ck_billing_account_currency'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_key')
    )
    op.create_index(op.f('ix_billing_accounts_external_customer_reference'), 'billing_accounts', ['external_customer_reference'], unique=False)
    op.create_index(op.f('ix_billing_accounts_status'), 'billing_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_billing_accounts_tenant_id'), 'billing_accounts', ['tenant_id'], unique=False)
    op.create_table('rate_card_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('rate_card_key', sa.String(length=120), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=500), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_until > effective_from', name='ck_rate_card_effective_window'),
    sa.CheckConstraint('length(currency) = 3', name='ck_rate_card_currency'),
    sa.CheckConstraint('revision > 0', name='ck_rate_card_revision'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'content_sha256'),
    sa.UniqueConstraint('tenant_id', 'rate_card_key', 'revision')
    )
    op.create_index(op.f('ix_rate_card_versions_effective_from'), 'rate_card_versions', ['effective_from'], unique=False)
    op.create_index(op.f('ix_rate_card_versions_effective_until'), 'rate_card_versions', ['effective_until'], unique=False)
    op.create_index(op.f('ix_rate_card_versions_rate_card_key'), 'rate_card_versions', ['rate_card_key'], unique=False)
    op.create_index(op.f('ix_rate_card_versions_tenant_id'), 'rate_card_versions', ['tenant_id'], unique=False)
    op.create_table('agent_client_subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_client_id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("actor_type IN ('agent', 'api_key')", name='ck_agent_client_subject_actor_type'),
    sa.ForeignKeyConstraint(['agent_client_id'], ['agent_clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_client_id', 'actor_type', 'subject_id')
    )
    op.create_index(op.f('ix_agent_client_subjects_active'), 'agent_client_subjects', ['active'], unique=False)
    op.create_index(op.f('ix_agent_client_subjects_agent_client_id'), 'agent_client_subjects', ['agent_client_id'], unique=False)
    op.create_index(op.f('ix_agent_client_subjects_subject_id'), 'agent_client_subjects', ['subject_id'], unique=False)
    op.create_index(op.f('ix_agent_client_subjects_tenant_id'), 'agent_client_subjects', ['tenant_id'], unique=False)
    op.create_table('commercial_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_key', sa.String(length=120), nullable=False),
    sa.Column('billing_account_id', sa.String(length=36), nullable=False),
    sa.Column('agent_client_id', sa.String(length=36), nullable=False),
    sa.Column('rate_card_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('consumed_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('reserved_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('consumed_units + reserved_units <= granted_units', name='ck_subscription_credit_conservation'),
    sa.CheckConstraint('consumed_units >= 0', name='ck_subscription_consumed_units'),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name='ck_subscription_window'),
    sa.CheckConstraint('granted_units >= 0', name='ck_subscription_granted_units'),
    sa.CheckConstraint('reserved_units >= 0', name='ck_subscription_reserved_units'),
    sa.ForeignKeyConstraint(['agent_client_id'], ['agent_clients.id'], ),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], ),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_client_id'),
    sa.UniqueConstraint('tenant_id', 'subscription_key')
    )
    op.create_index(op.f('ix_commercial_subscriptions_agent_client_id'), 'commercial_subscriptions', ['agent_client_id'], unique=False)
    op.create_index(op.f('ix_commercial_subscriptions_billing_account_id'), 'commercial_subscriptions', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_commercial_subscriptions_ends_at'), 'commercial_subscriptions', ['ends_at'], unique=False)
    op.create_index(op.f('ix_commercial_subscriptions_rate_card_version_id'), 'commercial_subscriptions', ['rate_card_version_id'], unique=False)
    op.create_index(op.f('ix_commercial_subscriptions_starts_at'), 'commercial_subscriptions', ['starts_at'], unique=False)
    op.create_index(op.f('ix_commercial_subscriptions_status'), 'commercial_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_commercial_subscriptions_tenant_id'), 'commercial_subscriptions', ['tenant_id'], unique=False)
    op.create_table('invoice_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('billing_account_id', sa.String(length=36), nullable=False),
    sa.Column('external_invoice_id', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_due >= 0', name='ck_invoice_amount_due'),
    sa.CheckConstraint('length(currency) = 3', name='ck_invoice_currency'),
    sa.CheckConstraint('period_end > period_start', name='ck_invoice_period'),
    sa.CheckConstraint('total_units >= 0', name='ck_invoice_total_units'),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_invoice_id')
    )
    op.create_index(op.f('ix_invoice_references_billing_account_id'), 'invoice_references', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_invoice_references_status'), 'invoice_references', ['status'], unique=False)
    op.create_index(op.f('ix_invoice_references_tenant_id'), 'invoice_references', ['tenant_id'], unique=False)
    op.create_table('rate_card_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('rate_card_version_id', sa.String(length=36), nullable=False),
    sa.Column('billing_class', sa.String(length=160), nullable=False),
    sa.Column('entitlement_key', sa.String(length=160), nullable=False),
    sa.Column('base_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('per_result_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('per_kib_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('max_result_rows', sa.Integer(), nullable=False),
    sa.CheckConstraint('base_units >= 0', name='ck_rate_card_item_base_units'),
    sa.CheckConstraint('max_result_rows > 0', name='ck_rate_card_item_max_rows'),
    sa.CheckConstraint('per_kib_units >= 0', name='ck_rate_card_item_kib_units'),
    sa.CheckConstraint('per_result_units >= 0', name='ck_rate_card_item_result_units'),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rate_card_version_id', 'billing_class')
    )
    op.create_index(op.f('ix_rate_card_items_billing_class'), 'rate_card_items', ['billing_class'], unique=False)
    op.create_index(op.f('ix_rate_card_items_entitlement_key'), 'rate_card_items', ['entitlement_key'], unique=False)
    op.create_index(op.f('ix_rate_card_items_rate_card_version_id'), 'rate_card_items', ['rate_card_version_id'], unique=False)
    op.create_index(op.f('ix_rate_card_items_tenant_id'), 'rate_card_items', ['tenant_id'], unique=False)
    op.create_table('billing_adjustments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('adjustment_key', sa.String(length=200), nullable=False),
    sa.Column('reverses_adjustment_id', sa.String(length=36), nullable=True),
    sa.Column('units_delta', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('created_by', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('units_delta != 0', name='ck_billing_adjustment_nonzero'),
    sa.ForeignKeyConstraint(['reverses_adjustment_id'], ['billing_adjustments.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['commercial_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'adjustment_key')
    )
    op.create_index(op.f('ix_billing_adjustments_created_at'), 'billing_adjustments', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_adjustments_reverses_adjustment_id'), 'billing_adjustments', ['reverses_adjustment_id'], unique=False)
    op.create_index(op.f('ix_billing_adjustments_subscription_id'), 'billing_adjustments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_adjustments_tenant_id'), 'billing_adjustments', ['tenant_id'], unique=False)
    op.create_table('commercial_entitlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('entitlement_key', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_result_rows', sa.Integer(), nullable=False),
    sa.Column('daily_unit_limit', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('data_domains', sa.JSON(), nullable=False),
    sa.Column('constraints_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('daily_unit_limit IS NULL OR daily_unit_limit > 0', name='ck_entitlement_daily_limit'),
    sa.CheckConstraint('max_result_rows > 0', name='ck_entitlement_max_rows'),
    sa.ForeignKeyConstraint(['subscription_id'], ['commercial_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'subscription_id', 'entitlement_key')
    )
    op.create_index(op.f('ix_commercial_entitlements_enabled'), 'commercial_entitlements', ['enabled'], unique=False)
    op.create_index(op.f('ix_commercial_entitlements_entitlement_key'), 'commercial_entitlements', ['entitlement_key'], unique=False)
    op.create_index(op.f('ix_commercial_entitlements_subscription_id'), 'commercial_entitlements', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_commercial_entitlements_tenant_id'), 'commercial_entitlements', ['tenant_id'], unique=False)
    op.create_table('credit_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('granted_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_reference', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > granted_at', name='ck_credit_grant_window'),
    sa.CheckConstraint('granted_units > 0', name='ck_credit_grant_units'),
    sa.ForeignKeyConstraint(['subscription_id'], ['commercial_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_reference')
    )
    op.create_index(op.f('ix_credit_grants_expires_at'), 'credit_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_credit_grants_granted_at'), 'credit_grants', ['granted_at'], unique=False)
    op.create_index(op.f('ix_credit_grants_subscription_id'), 'credit_grants', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_credit_grants_tenant_id'), 'credit_grants', ['tenant_id'], unique=False)
    op.create_table('usage_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('agent_client_id', sa.String(length=36), nullable=False),
    sa.Column('rate_card_item_id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=500), nullable=False),
    sa.Column('billing_class', sa.String(length=160), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('requested_result_limit', sa.Integer(), nullable=False),
    sa.Column('client_max_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('estimated_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('reserved_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('state', sa.Enum('RESERVED', 'SETTLED', 'RELEASED', 'EXPIRED', name='usagereservationstate'), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint("actor_type IN ('agent', 'api_key')", name='ck_usage_reservation_actor_type'),
    sa.CheckConstraint('client_max_units > 0', name='ck_usage_reservation_client_max'),
    sa.CheckConstraint('estimated_units >= 0', name='ck_usage_reservation_estimated'),
    sa.CheckConstraint('requested_result_limit > 0', name='ck_usage_reservation_result_limit'),
    sa.CheckConstraint('reserved_units > 0', name='ck_usage_reservation_reserved'),
    sa.ForeignKeyConstraint(['agent_client_id'], ['agent_clients.id'], ),
    sa.ForeignKeyConstraint(['rate_card_item_id'], ['rate_card_items.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['commercial_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_client_id', 'actor_type', 'subject_id', 'idempotency_key')
    )
    op.create_index('ix_usage_reservation_expiry', 'usage_reservations', ['tenant_id', 'state', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_usage_reservations_agent_client_id'), 'usage_reservations', ['agent_client_id'], unique=False)
    op.create_index(op.f('ix_usage_reservations_billing_class'), 'usage_reservations', ['billing_class'], unique=False)
    op.create_index(op.f('ix_usage_reservations_lease_expires_at'), 'usage_reservations', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_usage_reservations_rate_card_item_id'), 'usage_reservations', ['rate_card_item_id'], unique=False)
    op.create_index(op.f('ix_usage_reservations_request_id'), 'usage_reservations', ['request_id'], unique=False)
    op.create_index(op.f('ix_usage_reservations_state'), 'usage_reservations', ['state'], unique=False)
    op.create_index(op.f('ix_usage_reservations_subject_id'), 'usage_reservations', ['subject_id'], unique=False)
    op.create_index(op.f('ix_usage_reservations_subscription_id'), 'usage_reservations', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_reservations_tenant_id'), 'usage_reservations', ['tenant_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('billing_class', sa.String(length=160), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('response_bytes', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('result_sha256', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('response_bytes >= 0', name='ck_usage_event_response_bytes'),
    sa.CheckConstraint('result_count >= 0', name='ck_usage_event_result_count'),
    sa.ForeignKeyConstraint(['reservation_id'], ['usage_reservations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['commercial_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_key')
    )
    op.create_index(op.f('ix_usage_events_billing_class'), 'usage_events', ['billing_class'], unique=False)
    op.create_index(op.f('ix_usage_events_occurred_at'), 'usage_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_usage_events_reservation_id'), 'usage_events', ['reservation_id'], unique=True)
    op.create_index(op.f('ix_usage_events_subscription_id'), 'usage_events', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_events_tenant_id'), 'usage_events', ['tenant_id'], unique=False)
    op.create_table('usage_settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('settlement_key', sa.String(length=200), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('usage_event_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('rate_card_version_id', sa.String(length=36), nullable=False),
    sa.Column('charged_units', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('price_breakdown', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('charged_units >= 0', name='ck_usage_settlement_charged'),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['usage_reservations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['commercial_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usage_event_id'], ['usage_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'settlement_key')
    )
    op.create_index(op.f('ix_usage_settlements_created_at'), 'usage_settlements', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_settlements_rate_card_version_id'), 'usage_settlements', ['rate_card_version_id'], unique=False)
    op.create_index(op.f('ix_usage_settlements_reservation_id'), 'usage_settlements', ['reservation_id'], unique=True)
    op.create_index(op.f('ix_usage_settlements_subscription_id'), 'usage_settlements', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_settlements_tenant_id'), 'usage_settlements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_usage_settlements_usage_event_id'), 'usage_settlements', ['usage_event_id'], unique=True)
    op.create_table('commercial_ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=True),
    sa.Column('settlement_id', sa.String(length=36), nullable=True),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.Enum('CREDIT_GRANTED', 'USAGE_RESERVED', 'USAGE_SETTLED', 'RESERVATION_RELEASED', 'RESERVATION_EXPIRED', 'ADJUSTMENT', 'REVERSAL', name='commercialledgereventtype'), nullable=False),
    sa.Column('granted_delta', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('reserved_delta', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('consumed_delta', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['usage_reservations.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['usage_settlements.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['commercial_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_key')
    )
    op.create_index(op.f('ix_commercial_ledger_entries_event_type'), 'commercial_ledger_entries', ['event_type'], unique=False)
    op.create_index(op.f('ix_commercial_ledger_entries_occurred_at'), 'commercial_ledger_entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_commercial_ledger_entries_request_id'), 'commercial_ledger_entries', ['request_id'], unique=False)
    op.create_index(op.f('ix_commercial_ledger_entries_reservation_id'), 'commercial_ledger_entries', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_commercial_ledger_entries_settlement_id'), 'commercial_ledger_entries', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_commercial_ledger_entries_subscription_id'), 'commercial_ledger_entries', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_commercial_ledger_entries_tenant_id'), 'commercial_ledger_entries', ['tenant_id'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        predicate = "tenant_id = public.app_current_tenant_id()"
        for table in TENANT_TABLES:
            op.execute(sa.text(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY'))
            op.execute(sa.text(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY'))
            op.execute(
                sa.text(
                    f'CREATE POLICY "tenant_isolation" ON "{table}" '
                    f"USING ({predicate}) WITH CHECK ({predicate})"
                )
            )
        op.execute(
            sa.text(
                """
                CREATE OR REPLACE FUNCTION platform_private.reject_commercial_history_mutation()
                RETURNS trigger
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    RAISE EXCEPTION 'commercial history is append-only: %', TG_TABLE_NAME
                        USING ERRCODE = '55000';
                END;
                $$
                """
            )
        )
        for table in IMMUTABLE_TABLES:
            op.execute(
                sa.text(
                    f'CREATE TRIGGER "immutable_commercial_history" BEFORE UPDATE OR DELETE ON "{table}" '
                    "FOR EACH ROW EXECUTE FUNCTION platform_private.reject_commercial_history_mutation()"
                )
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for table in IMMUTABLE_TABLES:
            op.execute(sa.text(f'DROP TRIGGER IF EXISTS "immutable_commercial_history" ON "{table}"'))
        op.execute(sa.text("DROP FUNCTION IF EXISTS platform_private.reject_commercial_history_mutation()"))
        for table in reversed(TENANT_TABLES):
            op.execute(sa.text(f'DROP POLICY IF EXISTS "tenant_isolation" ON "{table}"'))
            op.execute(sa.text(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY'))
    op.drop_index(op.f('ix_commercial_ledger_entries_tenant_id'), table_name='commercial_ledger_entries')
    op.drop_index(op.f('ix_commercial_ledger_entries_subscription_id'), table_name='commercial_ledger_entries')
    op.drop_index(op.f('ix_commercial_ledger_entries_settlement_id'), table_name='commercial_ledger_entries')
    op.drop_index(op.f('ix_commercial_ledger_entries_reservation_id'), table_name='commercial_ledger_entries')
    op.drop_index(op.f('ix_commercial_ledger_entries_request_id'), table_name='commercial_ledger_entries')
    op.drop_index(op.f('ix_commercial_ledger_entries_occurred_at'), table_name='commercial_ledger_entries')
    op.drop_index(op.f('ix_commercial_ledger_entries_event_type'), table_name='commercial_ledger_entries')
    op.drop_table('commercial_ledger_entries')
    op.drop_index(op.f('ix_usage_settlements_usage_event_id'), table_name='usage_settlements')
    op.drop_index(op.f('ix_usage_settlements_tenant_id'), table_name='usage_settlements')
    op.drop_index(op.f('ix_usage_settlements_subscription_id'), table_name='usage_settlements')
    op.drop_index(op.f('ix_usage_settlements_reservation_id'), table_name='usage_settlements')
    op.drop_index(op.f('ix_usage_settlements_rate_card_version_id'), table_name='usage_settlements')
    op.drop_index(op.f('ix_usage_settlements_created_at'), table_name='usage_settlements')
    op.drop_table('usage_settlements')
    op.drop_index(op.f('ix_usage_events_tenant_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_subscription_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_reservation_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_occurred_at'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_billing_class'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_usage_reservations_tenant_id'), table_name='usage_reservations')
    op.drop_index(op.f('ix_usage_reservations_subscription_id'), table_name='usage_reservations')
    op.drop_index(op.f('ix_usage_reservations_subject_id'), table_name='usage_reservations')
    op.drop_index(op.f('ix_usage_reservations_state'), table_name='usage_reservations')
    op.drop_index(op.f('ix_usage_reservations_request_id'), table_name='usage_reservations')
    op.drop_index(op.f('ix_usage_reservations_rate_card_item_id'), table_name='usage_reservations')
    op.drop_index(op.f('ix_usage_reservations_lease_expires_at'), table_name='usage_reservations')
    op.drop_index(op.f('ix_usage_reservations_billing_class'), table_name='usage_reservations')
    op.drop_index(op.f('ix_usage_reservations_agent_client_id'), table_name='usage_reservations')
    op.drop_index('ix_usage_reservation_expiry', table_name='usage_reservations')
    op.drop_table('usage_reservations')
    op.drop_index(op.f('ix_credit_grants_tenant_id'), table_name='credit_grants')
    op.drop_index(op.f('ix_credit_grants_subscription_id'), table_name='credit_grants')
    op.drop_index(op.f('ix_credit_grants_granted_at'), table_name='credit_grants')
    op.drop_index(op.f('ix_credit_grants_expires_at'), table_name='credit_grants')
    op.drop_table('credit_grants')
    op.drop_index(op.f('ix_commercial_entitlements_tenant_id'), table_name='commercial_entitlements')
    op.drop_index(op.f('ix_commercial_entitlements_subscription_id'), table_name='commercial_entitlements')
    op.drop_index(op.f('ix_commercial_entitlements_entitlement_key'), table_name='commercial_entitlements')
    op.drop_index(op.f('ix_commercial_entitlements_enabled'), table_name='commercial_entitlements')
    op.drop_table('commercial_entitlements')
    op.drop_index(op.f('ix_billing_adjustments_tenant_id'), table_name='billing_adjustments')
    op.drop_index(op.f('ix_billing_adjustments_subscription_id'), table_name='billing_adjustments')
    op.drop_index(op.f('ix_billing_adjustments_reverses_adjustment_id'), table_name='billing_adjustments')
    op.drop_index(op.f('ix_billing_adjustments_created_at'), table_name='billing_adjustments')
    op.drop_table('billing_adjustments')
    op.drop_index(op.f('ix_rate_card_items_tenant_id'), table_name='rate_card_items')
    op.drop_index(op.f('ix_rate_card_items_rate_card_version_id'), table_name='rate_card_items')
    op.drop_index(op.f('ix_rate_card_items_entitlement_key'), table_name='rate_card_items')
    op.drop_index(op.f('ix_rate_card_items_billing_class'), table_name='rate_card_items')
    op.drop_table('rate_card_items')
    op.drop_index(op.f('ix_invoice_references_tenant_id'), table_name='invoice_references')
    op.drop_index(op.f('ix_invoice_references_status'), table_name='invoice_references')
    op.drop_index(op.f('ix_invoice_references_billing_account_id'), table_name='invoice_references')
    op.drop_table('invoice_references')
    op.drop_index(op.f('ix_commercial_subscriptions_tenant_id'), table_name='commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_subscriptions_status'), table_name='commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_subscriptions_starts_at'), table_name='commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_subscriptions_rate_card_version_id'), table_name='commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_subscriptions_ends_at'), table_name='commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_subscriptions_billing_account_id'), table_name='commercial_subscriptions')
    op.drop_index(op.f('ix_commercial_subscriptions_agent_client_id'), table_name='commercial_subscriptions')
    op.drop_table('commercial_subscriptions')
    op.drop_index(op.f('ix_agent_client_subjects_tenant_id'), table_name='agent_client_subjects')
    op.drop_index(op.f('ix_agent_client_subjects_subject_id'), table_name='agent_client_subjects')
    op.drop_index(op.f('ix_agent_client_subjects_agent_client_id'), table_name='agent_client_subjects')
    op.drop_index(op.f('ix_agent_client_subjects_active'), table_name='agent_client_subjects')
    op.drop_table('agent_client_subjects')
    op.drop_index(op.f('ix_rate_card_versions_tenant_id'), table_name='rate_card_versions')
    op.drop_index(op.f('ix_rate_card_versions_rate_card_key'), table_name='rate_card_versions')
    op.drop_index(op.f('ix_rate_card_versions_effective_until'), table_name='rate_card_versions')
    op.drop_index(op.f('ix_rate_card_versions_effective_from'), table_name='rate_card_versions')
    op.drop_table('rate_card_versions')
    op.drop_index(op.f('ix_billing_accounts_tenant_id'), table_name='billing_accounts')
    op.drop_index(op.f('ix_billing_accounts_status'), table_name='billing_accounts')
    op.drop_index(op.f('ix_billing_accounts_external_customer_reference'), table_name='billing_accounts')
    op.drop_table('billing_accounts')
    op.drop_index(op.f('ix_agent_clients_tenant_id'), table_name='agent_clients')
    op.drop_index(op.f('ix_agent_clients_active'), table_name='agent_clients')
    op.drop_table('agent_clients')
    # ### end Alembic commands ###
