"""add governed data factory

Revision ID: 332782d8b0cf
Revises: 4c22f51cb18e
Create Date: 2026-07-15 19:35:49.812088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332782d8b0cf'
down_revision: Union[str, Sequence[str], None] = '4c22f51cb18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TENANT_TABLES = (
    "data_sources",
    "extraction_runs",
    "ingestion_runs",
    "ingestion_findings",
    "knowledge_citations",
    "knowledge_links",
    "knowledge_page_versions",
    "knowledge_pages",
    "outbox_events",
    "review_tasks",
    "retrieval_projections",
    "source_assets",
    "source_versions",
    "staged_facts",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.Enum('FOLDER', name='datasourcetype'), nullable=False),
    sa.Column('root_uri', sa.Text(), nullable=False),
    sa.Column('credential_ref', sa.String(length=500), nullable=True),
    sa.Column('dataset_key', sa.String(length=80), nullable=False),
    sa.Column('include_globs', sa.JSON(), nullable=False),
    sa.Column('exclude_globs', sa.JSON(), nullable=False),
    sa.Column('routing_rules', sa.JSON(), nullable=False),
    sa.Column('stable_seconds', sa.Integer(), nullable=False),
    sa.Column('max_file_bytes', sa.Integer(), nullable=False),
    sa.Column('scan_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'PAUSED', 'UNAVAILABLE', 'DISABLED', name='datasourcestate'), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unavailable_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_file_bytes > 0', name='ck_data_source_max_file_bytes'),
    sa.CheckConstraint('scan_interval_seconds >= 10', name='ck_data_source_scan_interval'),
    sa.CheckConstraint('stable_seconds >= 0', name='ck_data_source_stable_seconds'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name'),
    sa.UniqueConstraint('tenant_id', 'root_uri')
    )
    op.create_index(op.f('ix_data_sources_dataset_key'), 'data_sources', ['dataset_key'], unique=False)
    op.create_index(op.f('ix_data_sources_last_scanned_at'), 'data_sources', ['last_scanned_at'], unique=False)
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_data_sources_state'), 'data_sources', ['state'], unique=False)
    op.create_index(op.f('ix_data_sources_tenant_id'), 'data_sources', ['tenant_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'PUBLISHED', 'FAILED', name='outboxstate'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_type'), 'outbox_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_state'), 'outbox_events', ['state'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_index('ix_outbox_state_available', 'outbox_events', ['state', 'available_at'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=200), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'PARTIAL', name='runstate'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_data_source_id'), 'ingestion_runs', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_heartbeat_at'), 'ingestion_runs', ['heartbeat_at'], unique=False)
    op.create_index('ix_ingestion_runs_source_started', 'ingestion_runs', ['data_source_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_started_at'), 'ingestion_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_state'), 'ingestion_runs', ['state'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_tenant_id'), 'ingestion_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_workflow_id'), 'ingestion_runs', ['workflow_id'], unique=True)
    op.create_table('ingestion_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_findings_code'), 'ingestion_findings', ['code'], unique=False)
    op.create_index(op.f('ix_ingestion_findings_ingestion_run_id'), 'ingestion_findings', ['ingestion_run_id'], unique=False)
    op.create_index('ix_ingestion_findings_run_stage', 'ingestion_findings', ['ingestion_run_id', 'stage'], unique=False)
    op.create_index(op.f('ix_ingestion_findings_stage'), 'ingestion_findings', ['stage'], unique=False)
    op.create_index(op.f('ix_ingestion_findings_tenant_id'), 'ingestion_findings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ingestion_findings_occurred_at'), 'ingestion_findings', ['occurred_at'], unique=False)
    op.create_table('knowledge_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('page_key', sa.String(length=240), nullable=False),
    sa.Column('page_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='knowledgepagestatus'), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'page_key')
    )
    op.create_index(op.f('ix_knowledge_pages_current_version_id'), 'knowledge_pages', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_pages_page_type'), 'knowledge_pages', ['page_type'], unique=False)
    op.create_index(op.f('ix_knowledge_pages_status'), 'knowledge_pages', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_pages_subject_entity_id'), 'knowledge_pages', ['subject_entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_pages_tenant_id'), 'knowledge_pages', ['tenant_id'], unique=False)
    op.create_index('ix_knowledge_pages_tenant_type_title', 'knowledge_pages', ['tenant_id', 'page_type', 'title'], unique=False)
    op.create_table('source_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('logical_path', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=1000), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.Column('media_type', sa.String(length=200), nullable=True),
    sa.Column('processing_mode', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'MISSING', 'SOURCE_UNAVAILABLE', 'DELETED', name='sourceassetstate'), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'data_source_id', 'logical_path')
    )
    op.create_index(op.f('ix_source_assets_current_version_id'), 'source_assets', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_source_assets_data_source_id'), 'source_assets', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_source_assets_extension'), 'source_assets', ['extension'], unique=False)
    op.create_index(op.f('ix_source_assets_last_seen_at'), 'source_assets', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_source_assets_processing_mode'), 'source_assets', ['processing_mode'], unique=False)
    op.create_index('ix_source_assets_source_seen', 'source_assets', ['tenant_id', 'data_source_id', 'last_seen_at'], unique=False)
    op.create_index(op.f('ix_source_assets_state'), 'source_assets', ['state'], unique=False)
    op.create_index(op.f('ix_source_assets_tenant_id'), 'source_assets', ['tenant_id'], unique=False)
    op.create_table('knowledge_page_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_page_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('compiler_version', sa.String(length=80), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('rendered_markdown', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_run_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_page_id'], ['knowledge_pages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'knowledge_page_id', 'content_sha256'),
    sa.UniqueConstraint('tenant_id', 'knowledge_page_id', 'version_number')
    )
    op.create_index(op.f('ix_knowledge_page_versions_content_sha256'), 'knowledge_page_versions', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_knowledge_page_versions_created_by_run_id'), 'knowledge_page_versions', ['created_by_run_id'], unique=False)
    op.create_index(op.f('ix_knowledge_page_versions_knowledge_page_id'), 'knowledge_page_versions', ['knowledge_page_id'], unique=False)
    op.create_index(op.f('ix_knowledge_page_versions_tenant_id'), 'knowledge_page_versions', ['tenant_id'], unique=False)
    op.create_table('retrieval_projections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_dataset_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('external_dataset_id', sa.String(length=160), nullable=False),
    sa.Column('external_document_id', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='stagestatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_dataset_id'], ['tenant_datasets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_document_id', 'tenant_dataset_id', 'engine')
    )
    op.create_index(op.f('ix_retrieval_projections_engine'), 'retrieval_projections', ['engine'], unique=False)
    op.create_index(op.f('ix_retrieval_projections_external_dataset_id'), 'retrieval_projections', ['external_dataset_id'], unique=False)
    op.create_index(op.f('ix_retrieval_projections_external_document_id'), 'retrieval_projections', ['external_document_id'], unique=False)
    op.create_index(op.f('ix_retrieval_projections_last_reconciled_at'), 'retrieval_projections', ['last_reconciled_at'], unique=False)
    op.create_index(op.f('ix_retrieval_projections_source_document_id'), 'retrieval_projections', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_retrieval_projections_status'), 'retrieval_projections', ['status'], unique=False)
    op.create_index(op.f('ix_retrieval_projections_tenant_dataset_id'), 'retrieval_projections', ['tenant_dataset_id'], unique=False)
    op.create_index(op.f('ix_retrieval_projections_tenant_id'), 'retrieval_projections', ['tenant_id'], unique=False)
    op.create_index('ix_retrieval_projection_status', 'retrieval_projections', ['tenant_id', 'engine', 'status'], unique=False)
    op.create_table('source_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_asset_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('DISCOVERED', 'SNAPSHOTTED', 'PARSED', 'INDEXED', 'GOVERNANCE_PENDING', 'REVIEW_PENDING', 'PUBLISHED', 'ASSET_ONLY', 'FAILED', name='sourceversionstate'), nullable=False),
    sa.Column('snapshot_status', sa.Enum('NOT_STARTED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='stagestatus'), nullable=False),
    sa.Column('parse_status', sa.Enum('NOT_STARTED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='stagestatus'), nullable=False),
    sa.Column('retrieval_status', sa.Enum('NOT_STARTED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='stagestatus'), nullable=False),
    sa.Column('governance_status', sa.Enum('NOT_STARTED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='stagestatus'), nullable=False),
    sa.Column('raw_object_uri', sa.Text(), nullable=True),
    sa.Column('extracted_text_object_uri', sa.Text(), nullable=True),
    sa.Column('extracted_text_sha256', sa.String(length=64), nullable=True),
    sa.Column('parser_name', sa.String(length=120), nullable=True),
    sa.Column('parser_version', sa.String(length=80), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('retrieval_projection_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_source_version_size'),
    sa.CheckConstraint('version_number > 0', name='ck_source_version_number'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['source_assets.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['retrieval_projection_id'], ['retrieval_projections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_asset_id', 'content_sha256'),
    sa.UniqueConstraint('tenant_id', 'source_asset_id', 'version_number')
    )
    op.create_index(op.f('ix_source_versions_content_sha256'), 'source_versions', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_source_versions_discovered_at'), 'source_versions', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_source_versions_error_code'), 'source_versions', ['error_code'], unique=False)
    op.create_index(op.f('ix_source_versions_extracted_text_sha256'), 'source_versions', ['extracted_text_sha256'], unique=False)
    op.create_index(op.f('ix_source_versions_source_asset_id'), 'source_versions', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_source_versions_source_document_id'), 'source_versions', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_source_versions_retrieval_projection_id'), 'source_versions', ['retrieval_projection_id'], unique=False)
    op.create_index(op.f('ix_source_versions_snapshot_status'), 'source_versions', ['snapshot_status'], unique=False)
    op.create_index(op.f('ix_source_versions_parse_status'), 'source_versions', ['parse_status'], unique=False)
    op.create_index(op.f('ix_source_versions_retrieval_status'), 'source_versions', ['retrieval_status'], unique=False)
    op.create_index(op.f('ix_source_versions_governance_status'), 'source_versions', ['governance_status'], unique=False)
    op.create_index(op.f('ix_source_versions_state'), 'source_versions', ['state'], unique=False)
    op.create_index(op.f('ix_source_versions_tenant_id'), 'source_versions', ['tenant_id'], unique=False)
    op.create_index('ix_source_versions_tenant_state', 'source_versions', ['tenant_id', 'state', 'discovered_at'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_version_id', sa.String(length=36), nullable=False),
    sa.Column('schema_name', sa.String(length=120), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('model_provider', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('prompt_sha256', sa.String(length=64), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'PARTIAL', name='runstate'), nullable=False),
    sa.Column('structured_output', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_version_id', 'schema_name', 'schema_version', 'input_sha256')
    )
    op.create_index(op.f('ix_extraction_runs_schema_name'), 'extraction_runs', ['schema_name'], unique=False)
    op.create_index(op.f('ix_extraction_runs_source_version_id'), 'extraction_runs', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_extraction_runs_status'), 'extraction_runs', ['status'], unique=False)
    op.create_index(op.f('ix_extraction_runs_tenant_id'), 'extraction_runs', ['tenant_id'], unique=False)
    op.create_index('ix_extraction_runs_version_status', 'extraction_runs', ['source_version_id', 'status'], unique=False)
    op.create_table('knowledge_citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('page_version_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_claim_id', sa.String(length=36), nullable=True),
    sa.Column('source_locator', sa.String(length=500), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_claim_id'], ['evidence_claims.id'], ),
    sa.ForeignKeyConstraint(['page_version_id'], ['knowledge_page_versions.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'page_version_id', 'ordinal')
    )
    op.create_index(op.f('ix_knowledge_citations_evidence_claim_id'), 'knowledge_citations', ['evidence_claim_id'], unique=False)
    op.create_index(op.f('ix_knowledge_citations_page_version_id'), 'knowledge_citations', ['page_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_citations_source_document_id'), 'knowledge_citations', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_citations_tenant_id'), 'knowledge_citations', ['tenant_id'], unique=False)
    op.create_table('knowledge_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('page_version_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=120), nullable=False),
    sa.Column('target_key', sa.String(length=240), nullable=False),
    sa.Column('target_page_id', sa.String(length=36), nullable=True),
    sa.Column('target_entity_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_knowledge_link_confidence'),
    sa.ForeignKeyConstraint(['page_version_id'], ['knowledge_page_versions.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_page_id'], ['knowledge_pages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'page_version_id', 'relationship', 'target_key')
    )
    op.create_index(op.f('ix_knowledge_links_page_version_id'), 'knowledge_links', ['page_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_links_relationship'), 'knowledge_links', ['relationship'], unique=False)
    op.create_index(op.f('ix_knowledge_links_target_entity_id'), 'knowledge_links', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_knowledge_links_target_key'), 'knowledge_links', ['target_key'], unique=False)
    op.create_index(op.f('ix_knowledge_links_target_page_id'), 'knowledge_links', ['target_page_id'], unique=False)
    op.create_index(op.f('ix_knowledge_links_tenant_id'), 'knowledge_links', ['tenant_id'], unique=False)
    op.create_table('staged_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_run_id', sa.String(length=36), nullable=False),
    sa.Column('fact_kind', sa.String(length=80), nullable=False),
    sa.Column('fact_key', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('source_locator', sa.String(length=500), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'VALIDATED', 'CONFLICT', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', name='governancestatus'), nullable=False),
    sa.Column('quality_findings', sa.JSON(), nullable=False),
    sa.Column('conflict_with_ids', sa.JSON(), nullable=False),
    sa.Column('published_resource_type', sa.String(length=80), nullable=True),
    sa.Column('published_resource_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_staged_fact_confidence'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'extraction_run_id', 'fact_key')
    )
    op.create_index(op.f('ix_staged_facts_extraction_run_id'), 'staged_facts', ['extraction_run_id'], unique=False)
    op.create_index(op.f('ix_staged_facts_fact_kind'), 'staged_facts', ['fact_kind'], unique=False)
    op.create_index(op.f('ix_staged_facts_published_resource_id'), 'staged_facts', ['published_resource_id'], unique=False)
    op.create_index(op.f('ix_staged_facts_source_document_id'), 'staged_facts', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_staged_facts_status'), 'staged_facts', ['status'], unique=False)
    op.create_index(op.f('ix_staged_facts_tenant_id'), 'staged_facts', ['tenant_id'], unique=False)
    op.create_index('ix_staged_facts_tenant_kind_status', 'staged_facts', ['tenant_id', 'fact_kind', 'status'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('staged_fact_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'VALIDATED', 'CONFLICT', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', name='governancestatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staged_fact_id'], ['staged_facts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_assigned_user_id'), 'review_tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_decided_by_user_id'), 'review_tasks', ['decided_by_user_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_priority'), 'review_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_review_tasks_staged_fact_id'), 'review_tasks', ['staged_fact_id'], unique=True)
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_review_tasks_tenant_id'), 'review_tasks', ['tenant_id'], unique=False)
    op.create_index('ix_review_tasks_tenant_status_priority', 'review_tasks', ['tenant_id', 'status', 'priority'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        predicate = "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')"
        for table in TENANT_TABLES:
            op.execute(sa.text(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY'))
            op.execute(sa.text(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY'))
            op.execute(
                sa.text(
                    f'CREATE POLICY "tenant_isolation" ON "{table}" '
                    f"USING ({predicate}) WITH CHECK ({predicate})"
                )
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for table in reversed(TENANT_TABLES):
            op.execute(sa.text(f'DROP POLICY IF EXISTS "tenant_isolation" ON "{table}"'))
            op.execute(sa.text(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY'))
    op.drop_index('ix_review_tasks_tenant_status_priority', table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_tenant_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_staged_fact_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_priority'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_decided_by_user_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_assigned_user_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index('ix_staged_facts_tenant_kind_status', table_name='staged_facts')
    op.drop_index(op.f('ix_staged_facts_tenant_id'), table_name='staged_facts')
    op.drop_index(op.f('ix_staged_facts_status'), table_name='staged_facts')
    op.drop_index(op.f('ix_staged_facts_source_document_id'), table_name='staged_facts')
    op.drop_index(op.f('ix_staged_facts_published_resource_id'), table_name='staged_facts')
    op.drop_index(op.f('ix_staged_facts_fact_kind'), table_name='staged_facts')
    op.drop_index(op.f('ix_staged_facts_extraction_run_id'), table_name='staged_facts')
    op.drop_table('staged_facts')
    op.drop_index(op.f('ix_knowledge_links_tenant_id'), table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_target_page_id'), table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_target_key'), table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_target_entity_id'), table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_relationship'), table_name='knowledge_links')
    op.drop_index(op.f('ix_knowledge_links_page_version_id'), table_name='knowledge_links')
    op.drop_table('knowledge_links')
    op.drop_index(op.f('ix_knowledge_citations_tenant_id'), table_name='knowledge_citations')
    op.drop_index(op.f('ix_knowledge_citations_source_document_id'), table_name='knowledge_citations')
    op.drop_index(op.f('ix_knowledge_citations_page_version_id'), table_name='knowledge_citations')
    op.drop_index(op.f('ix_knowledge_citations_evidence_claim_id'), table_name='knowledge_citations')
    op.drop_table('knowledge_citations')
    op.drop_index('ix_extraction_runs_version_status', table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_tenant_id'), table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_status'), table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_source_version_id'), table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_schema_name'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index('ix_source_versions_tenant_state', table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_tenant_id'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_state'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_retrieval_projection_id'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_source_document_id'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_snapshot_status'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_parse_status'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_retrieval_status'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_governance_status'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_source_asset_id'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_extracted_text_sha256'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_error_code'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_discovered_at'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_content_sha256'), table_name='source_versions')
    op.drop_table('source_versions')
    op.drop_index('ix_retrieval_projection_status', table_name='retrieval_projections')
    op.drop_index(op.f('ix_retrieval_projections_tenant_id'), table_name='retrieval_projections')
    op.drop_index(op.f('ix_retrieval_projections_tenant_dataset_id'), table_name='retrieval_projections')
    op.drop_index(op.f('ix_retrieval_projections_status'), table_name='retrieval_projections')
    op.drop_index(op.f('ix_retrieval_projections_source_document_id'), table_name='retrieval_projections')
    op.drop_index(op.f('ix_retrieval_projections_last_reconciled_at'), table_name='retrieval_projections')
    op.drop_index(op.f('ix_retrieval_projections_external_document_id'), table_name='retrieval_projections')
    op.drop_index(op.f('ix_retrieval_projections_external_dataset_id'), table_name='retrieval_projections')
    op.drop_index(op.f('ix_retrieval_projections_engine'), table_name='retrieval_projections')
    op.drop_table('retrieval_projections')
    op.drop_index(op.f('ix_knowledge_page_versions_tenant_id'), table_name='knowledge_page_versions')
    op.drop_index(op.f('ix_knowledge_page_versions_knowledge_page_id'), table_name='knowledge_page_versions')
    op.drop_index(op.f('ix_knowledge_page_versions_created_by_run_id'), table_name='knowledge_page_versions')
    op.drop_index(op.f('ix_knowledge_page_versions_content_sha256'), table_name='knowledge_page_versions')
    op.drop_table('knowledge_page_versions')
    op.drop_index(op.f('ix_source_assets_tenant_id'), table_name='source_assets')
    op.drop_index(op.f('ix_source_assets_state'), table_name='source_assets')
    op.drop_index('ix_source_assets_source_seen', table_name='source_assets')
    op.drop_index(op.f('ix_source_assets_processing_mode'), table_name='source_assets')
    op.drop_index(op.f('ix_source_assets_last_seen_at'), table_name='source_assets')
    op.drop_index(op.f('ix_source_assets_extension'), table_name='source_assets')
    op.drop_index(op.f('ix_source_assets_data_source_id'), table_name='source_assets')
    op.drop_index(op.f('ix_source_assets_current_version_id'), table_name='source_assets')
    op.drop_table('source_assets')
    op.drop_index('ix_knowledge_pages_tenant_type_title', table_name='knowledge_pages')
    op.drop_index(op.f('ix_knowledge_pages_tenant_id'), table_name='knowledge_pages')
    op.drop_index(op.f('ix_knowledge_pages_subject_entity_id'), table_name='knowledge_pages')
    op.drop_index(op.f('ix_knowledge_pages_status'), table_name='knowledge_pages')
    op.drop_index(op.f('ix_knowledge_pages_page_type'), table_name='knowledge_pages')
    op.drop_index(op.f('ix_knowledge_pages_current_version_id'), table_name='knowledge_pages')
    op.drop_table('knowledge_pages')
    op.drop_index(op.f('ix_ingestion_findings_occurred_at'), table_name='ingestion_findings')
    op.drop_index(op.f('ix_ingestion_findings_tenant_id'), table_name='ingestion_findings')
    op.drop_index(op.f('ix_ingestion_findings_stage'), table_name='ingestion_findings')
    op.drop_index('ix_ingestion_findings_run_stage', table_name='ingestion_findings')
    op.drop_index(op.f('ix_ingestion_findings_ingestion_run_id'), table_name='ingestion_findings')
    op.drop_index(op.f('ix_ingestion_findings_code'), table_name='ingestion_findings')
    op.drop_table('ingestion_findings')
    op.drop_index(op.f('ix_ingestion_runs_workflow_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_tenant_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_state'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_started_at'), table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_source_started', table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_heartbeat_at'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_data_source_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_outbox_state_available', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_state'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_data_sources_tenant_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_state'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_last_scanned_at'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_dataset_key'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
