"""initial pharmaceutical intelligence schema

Revision ID: 8f2d23b59db2
Revises:
Create Date: 2026-07-15 17:22:26.323818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2d23b59db2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_hash')
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('DRUG', 'TARGET', 'DISEASE', 'ORGANIZATION', 'CLINICAL_TRIAL', 'PATENT', 'TRANSACTION', 'PRODUCT', 'TECHNOLOGY', 'PERSON', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'VERIFIED', 'REJECTED', 'SUPERSEDED', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'normalized_name')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_review_status'), 'entities', ['review_status'], unique=False)
    op.create_index(op.f('ix_entities_tenant_id'), 'entities', ['tenant_id'], unique=False)
    op.create_index('ix_entities_tenant_type_name', 'entities', ['tenant_id', 'entity_type', 'name'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('canonical_uri', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('ragflow_dataset_id', sa.String(length=64), nullable=True),
    sa.Column('ragflow_document_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'content_sha256')
    )
    op.create_index(op.f('ix_source_documents_content_sha256'), 'source_documents', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_source_documents_ragflow_dataset_id'), 'source_documents', ['ragflow_dataset_id'], unique=False)
    op.create_index(op.f('ix_source_documents_ragflow_document_id'), 'source_documents', ['ragflow_document_id'], unique=False)
    op.create_index(op.f('ix_source_documents_source_type'), 'source_documents', ['source_type'], unique=False)
    op.create_index(op.f('ix_source_documents_tenant_id'), 'source_documents', ['tenant_id'], unique=False)
    op.create_table('assays',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('source_assay_id', sa.String(length=160), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=True),
    sa.Column('assay_type', sa.String(length=80), nullable=True),
    sa.Column('assay_format', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organism', sa.String(length=160), nullable=True),
    sa.Column('cell_line', sa.String(length=160), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_system', 'source_assay_id')
    )
    op.create_index(op.f('ix_assays_assay_format'), 'assays', ['assay_format'], unique=False)
    op.create_index(op.f('ix_assays_assay_type'), 'assays', ['assay_type'], unique=False)
    op.create_index(op.f('ix_assays_source_assay_id'), 'assays', ['source_assay_id'], unique=False)
    op.create_index(op.f('ix_assays_source_system'), 'assays', ['source_system'], unique=False)
    op.create_index(op.f('ix_assays_target_entity_id'), 'assays', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_assays_tenant_id'), 'assays', ['tenant_id'], unique=False)
    op.create_table('clinical_trial_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('registry', sa.String(length=80), nullable=False),
    sa.Column('registry_id', sa.String(length=80), nullable=False),
    sa.Column('official_title', sa.Text(), nullable=False),
    sa.Column('overall_status', sa.String(length=100), nullable=True),
    sa.Column('phases', sa.JSON(), nullable=False),
    sa.Column('study_type', sa.String(length=80), nullable=True),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interventions', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('sponsors', sa.JSON(), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('last_update_posted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'registry', 'registry_id')
    )
    op.create_index(op.f('ix_clinical_trial_profiles_entity_id'), 'clinical_trial_profiles', ['entity_id'], unique=False)
    op.create_index(op.f('ix_clinical_trial_profiles_last_update_posted'), 'clinical_trial_profiles', ['last_update_posted'], unique=False)
    op.create_index(op.f('ix_clinical_trial_profiles_overall_status'), 'clinical_trial_profiles', ['overall_status'], unique=False)
    op.create_index(op.f('ix_clinical_trial_profiles_registry'), 'clinical_trial_profiles', ['registry'], unique=False)
    op.create_index(op.f('ix_clinical_trial_profiles_registry_id'), 'clinical_trial_profiles', ['registry_id'], unique=False)
    op.create_index(op.f('ix_clinical_trial_profiles_study_type'), 'clinical_trial_profiles', ['study_type'], unique=False)
    op.create_index(op.f('ix_clinical_trial_profiles_tenant_id'), 'clinical_trial_profiles', ['tenant_id'], unique=False)
    op.create_table('compound_structures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_smiles', sa.Text(), nullable=False),
    sa.Column('isomeric_smiles', sa.Text(), nullable=True),
    sa.Column('standard_inchi', sa.Text(), nullable=True),
    sa.Column('standard_inchi_key', sa.String(length=27), nullable=False),
    sa.Column('molecular_formula', sa.String(length=120), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.Column('exact_mass', sa.Float(), nullable=True),
    sa.Column('structure_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'standard_inchi_key')
    )
    op.create_index('ix_compound_structure_entity', 'compound_structures', ['tenant_id', 'entity_id'], unique=False)
    op.create_index(op.f('ix_compound_structures_entity_id'), 'compound_structures', ['entity_id'], unique=False)
    op.create_index(op.f('ix_compound_structures_standard_inchi_key'), 'compound_structures', ['standard_inchi_key'], unique=False)
    op.create_index(op.f('ix_compound_structures_tenant_id'), 'compound_structures', ['tenant_id'], unique=False)
    op.create_table('deal_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('deal_type', sa.String(length=100), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parties', sa.JSON(), nullable=False),
    sa.Column('asset_entity_ids', sa.JSON(), nullable=False),
    sa.Column('territory', sa.String(length=240), nullable=True),
    sa.Column('upfront_amount', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('total_potential_amount', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_id')
    )
    op.create_index(op.f('ix_deal_profiles_announced_at'), 'deal_profiles', ['announced_at'], unique=False)
    op.create_index(op.f('ix_deal_profiles_deal_type'), 'deal_profiles', ['deal_type'], unique=False)
    op.create_index(op.f('ix_deal_profiles_entity_id'), 'deal_profiles', ['entity_id'], unique=False)
    op.create_index(op.f('ix_deal_profiles_tenant_id'), 'deal_profiles', ['tenant_id'], unique=False)
    op.create_table('development_programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('drug_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=True),
    sa.Column('disease_entity_id', sa.String(length=36), nullable=True),
    sa.Column('organization_entity_id', sa.String(length=36), nullable=True),
    sa.Column('modality', sa.String(length=120), nullable=True),
    sa.Column('mechanism_of_action', sa.String(length=240), nullable=True),
    sa.Column('phase', sa.Enum('DISCOVERY', 'PRECLINICAL', 'IND', 'PHASE_1', 'PHASE_1_2', 'PHASE_2', 'PHASE_2_3', 'PHASE_3', 'FILED', 'APPROVED', 'DISCONTINUED', name='developmentphase'), nullable=False),
    sa.Column('status_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geography', sa.String(length=120), nullable=True),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disease_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['drug_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['organization_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'drug_entity_id', 'disease_entity_id', 'organization_entity_id')
    )
    op.create_index(op.f('ix_development_programs_disease_entity_id'), 'development_programs', ['disease_entity_id'], unique=False)
    op.create_index(op.f('ix_development_programs_drug_entity_id'), 'development_programs', ['drug_entity_id'], unique=False)
    op.create_index(op.f('ix_development_programs_geography'), 'development_programs', ['geography'], unique=False)
    op.create_index(op.f('ix_development_programs_modality'), 'development_programs', ['modality'], unique=False)
    op.create_index(op.f('ix_development_programs_organization_entity_id'), 'development_programs', ['organization_entity_id'], unique=False)
    op.create_index(op.f('ix_development_programs_phase'), 'development_programs', ['phase'], unique=False)
    op.create_index(op.f('ix_development_programs_status_date'), 'development_programs', ['status_date'], unique=False)
    op.create_index(op.f('ix_development_programs_target_entity_id'), 'development_programs', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_development_programs_tenant_id'), 'development_programs', ['tenant_id'], unique=False)
    op.create_index('ix_program_target_phase', 'development_programs', ['tenant_id', 'target_entity_id', 'phase'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=500), nullable=False),
    sa.Column('normalized_alias', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_id', 'normalized_alias')
    )
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_normalized_alias'), 'entity_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_entity_aliases_tenant_id'), 'entity_aliases', ['tenant_id'], unique=False)
    op.create_table('evidence_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('predicate', sa.String(length=120), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_locator', sa.String(length=500), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'VERIFIED', 'REJECTED', 'SUPERSEDED', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claims_entity_predicate', 'evidence_claims', ['tenant_id', 'subject_id', 'predicate'], unique=False)
    op.create_index(op.f('ix_evidence_claims_object_id'), 'evidence_claims', ['object_id'], unique=False)
    op.create_index(op.f('ix_evidence_claims_predicate'), 'evidence_claims', ['predicate'], unique=False)
    op.create_index(op.f('ix_evidence_claims_review_status'), 'evidence_claims', ['review_status'], unique=False)
    op.create_index(op.f('ix_evidence_claims_source_document_id'), 'evidence_claims', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_evidence_claims_subject_id'), 'evidence_claims', ['subject_id'], unique=False)
    op.create_index(op.f('ix_evidence_claims_tenant_id'), 'evidence_claims', ['tenant_id'], unique=False)
    op.create_table('ingestion_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('dataset_key', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'REGISTERED', 'UPLOADED', 'PARSING', 'READY', 'FAILED', 'SOURCE_UNAVAILABLE', 'EXCLUDED', name='assetstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_path')
    )
    op.create_index(op.f('ix_ingestion_assets_content_sha256'), 'ingestion_assets', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_ingestion_assets_dataset_key'), 'ingestion_assets', ['dataset_key'], unique=False)
    op.create_index(op.f('ix_ingestion_assets_file_type'), 'ingestion_assets', ['file_type'], unique=False)
    op.create_index(op.f('ix_ingestion_assets_status'), 'ingestion_assets', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_assets_tenant_id'), 'ingestion_assets', ['tenant_id'], unique=False)
    op.create_table('patent_families',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('family_identifier', sa.String(length=160), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('priority_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applicants', sa.JSON(), nullable=False),
    sa.Column('inventors', sa.JSON(), nullable=False),
    sa.Column('publications', sa.JSON(), nullable=False),
    sa.Column('legal_status', sa.String(length=120), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_entity_ids', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'family_identifier')
    )
    op.create_index(op.f('ix_patent_families_entity_id'), 'patent_families', ['entity_id'], unique=False)
    op.create_index(op.f('ix_patent_families_family_identifier'), 'patent_families', ['family_identifier'], unique=False)
    op.create_index(op.f('ix_patent_families_legal_status'), 'patent_families', ['legal_status'], unique=False)
    op.create_index(op.f('ix_patent_families_priority_date'), 'patent_families', ['priority_date'], unique=False)
    op.create_index(op.f('ix_patent_families_tenant_id'), 'patent_families', ['tenant_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('predicate', sa.String(length=120), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_status', sa.Enum('DRAFT', 'VERIFIED', 'REJECTED', 'SUPERSEDED', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'subject_id', 'predicate', 'object_id', 'valid_from')
    )
    op.create_index(op.f('ix_relationships_object_id'), 'relationships', ['object_id'], unique=False)
    op.create_index(op.f('ix_relationships_predicate'), 'relationships', ['predicate'], unique=False)
    op.create_index(op.f('ix_relationships_subject_id'), 'relationships', ['subject_id'], unique=False)
    op.create_index('ix_relationships_subject_predicate', 'relationships', ['tenant_id', 'subject_id', 'predicate'], unique=False)
    op.create_index(op.f('ix_relationships_tenant_id'), 'relationships', ['tenant_id'], unique=False)
    op.create_table('research_bundles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_key_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('resolved_entity_ids', sa.JSON(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_sha256')
    )
    op.create_index(op.f('ix_research_bundles_requested_by_key_id'), 'research_bundles', ['requested_by_key_id'], unique=False)
    op.create_index(op.f('ix_research_bundles_tenant_id'), 'research_bundles', ['tenant_id'], unique=False)
    op.create_table('target_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('gene_symbol', sa.String(length=80), nullable=True),
    sa.Column('uniprot_accession', sa.String(length=20), nullable=True),
    sa.Column('organism', sa.String(length=120), nullable=False),
    sa.Column('target_class', sa.String(length=160), nullable=True),
    sa.Column('sequence', sa.Text(), nullable=True),
    sa.Column('function_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_id')
    )
    op.create_index(op.f('ix_target_profiles_entity_id'), 'target_profiles', ['entity_id'], unique=False)
    op.create_index(op.f('ix_target_profiles_gene_symbol'), 'target_profiles', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_target_profiles_target_class'), 'target_profiles', ['target_class'], unique=False)
    op.create_index(op.f('ix_target_profiles_tenant_id'), 'target_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_target_profiles_uniprot_accession'), 'target_profiles', ['uniprot_accession'], unique=False)
    op.create_table('activity_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('source_activity_id', sa.String(length=160), nullable=False),
    sa.Column('assay_id', sa.String(length=36), nullable=False),
    sa.Column('compound_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=True),
    sa.Column('reported_type', sa.String(length=80), nullable=False),
    sa.Column('reported_relation', sa.Enum('EQUAL', 'LESS_THAN', 'LESS_OR_EQUAL', 'GREATER_THAN', 'GREATER_OR_EQUAL', 'APPROXIMATE', name='measurementrelation'), nullable=False),
    sa.Column('reported_value', sa.String(length=120), nullable=False),
    sa.Column('reported_units', sa.String(length=40), nullable=True),
    sa.Column('standard_type', sa.String(length=80), nullable=True),
    sa.Column('standard_relation', sa.Enum('EQUAL', 'LESS_THAN', 'LESS_OR_EQUAL', 'GREATER_THAN', 'GREATER_OR_EQUAL', 'APPROXIMATE', name='measurementrelation'), nullable=True),
    sa.Column('standard_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('standard_units', sa.String(length=40), nullable=True),
    sa.Column('pchembl_value', sa.Float(), nullable=True),
    sa.Column('qualifiers', sa.JSON(), nullable=False),
    sa.Column('validity_comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assay_id'], ['assays.id'], ),
    sa.ForeignKeyConstraint(['compound_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_system', 'source_activity_id')
    )
    op.create_index('ix_activity_compound', 'activity_measurements', ['tenant_id', 'compound_entity_id'], unique=False)
    op.create_index(op.f('ix_activity_measurements_assay_id'), 'activity_measurements', ['assay_id'], unique=False)
    op.create_index(op.f('ix_activity_measurements_compound_entity_id'), 'activity_measurements', ['compound_entity_id'], unique=False)
    op.create_index(op.f('ix_activity_measurements_pchembl_value'), 'activity_measurements', ['pchembl_value'], unique=False)
    op.create_index(op.f('ix_activity_measurements_source_activity_id'), 'activity_measurements', ['source_activity_id'], unique=False)
    op.create_index(op.f('ix_activity_measurements_source_system'), 'activity_measurements', ['source_system'], unique=False)
    op.create_index(op.f('ix_activity_measurements_standard_type'), 'activity_measurements', ['standard_type'], unique=False)
    op.create_index(op.f('ix_activity_measurements_target_entity_id'), 'activity_measurements', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_activity_measurements_tenant_id'), 'activity_measurements', ['tenant_id'], unique=False)
    op.create_index('ix_activity_target_type_value', 'activity_measurements', ['tenant_id', 'target_entity_id', 'standard_type', 'standard_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_target_type_value', table_name='activity_measurements')
    op.drop_index(op.f('ix_activity_measurements_tenant_id'), table_name='activity_measurements')
    op.drop_index(op.f('ix_activity_measurements_target_entity_id'), table_name='activity_measurements')
    op.drop_index(op.f('ix_activity_measurements_standard_type'), table_name='activity_measurements')
    op.drop_index(op.f('ix_activity_measurements_source_system'), table_name='activity_measurements')
    op.drop_index(op.f('ix_activity_measurements_source_activity_id'), table_name='activity_measurements')
    op.drop_index(op.f('ix_activity_measurements_pchembl_value'), table_name='activity_measurements')
    op.drop_index(op.f('ix_activity_measurements_compound_entity_id'), table_name='activity_measurements')
    op.drop_index(op.f('ix_activity_measurements_assay_id'), table_name='activity_measurements')
    op.drop_index('ix_activity_compound', table_name='activity_measurements')
    op.drop_table('activity_measurements')
    op.drop_index(op.f('ix_target_profiles_uniprot_accession'), table_name='target_profiles')
    op.drop_index(op.f('ix_target_profiles_tenant_id'), table_name='target_profiles')
    op.drop_index(op.f('ix_target_profiles_target_class'), table_name='target_profiles')
    op.drop_index(op.f('ix_target_profiles_gene_symbol'), table_name='target_profiles')
    op.drop_index(op.f('ix_target_profiles_entity_id'), table_name='target_profiles')
    op.drop_table('target_profiles')
    op.drop_index(op.f('ix_research_bundles_tenant_id'), table_name='research_bundles')
    op.drop_index(op.f('ix_research_bundles_requested_by_key_id'), table_name='research_bundles')
    op.drop_table('research_bundles')
    op.drop_index(op.f('ix_relationships_tenant_id'), table_name='relationships')
    op.drop_index('ix_relationships_subject_predicate', table_name='relationships')
    op.drop_index(op.f('ix_relationships_subject_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_predicate'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_object_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_patent_families_tenant_id'), table_name='patent_families')
    op.drop_index(op.f('ix_patent_families_priority_date'), table_name='patent_families')
    op.drop_index(op.f('ix_patent_families_legal_status'), table_name='patent_families')
    op.drop_index(op.f('ix_patent_families_family_identifier'), table_name='patent_families')
    op.drop_index(op.f('ix_patent_families_entity_id'), table_name='patent_families')
    op.drop_table('patent_families')
    op.drop_index(op.f('ix_ingestion_assets_tenant_id'), table_name='ingestion_assets')
    op.drop_index(op.f('ix_ingestion_assets_status'), table_name='ingestion_assets')
    op.drop_index(op.f('ix_ingestion_assets_file_type'), table_name='ingestion_assets')
    op.drop_index(op.f('ix_ingestion_assets_dataset_key'), table_name='ingestion_assets')
    op.drop_index(op.f('ix_ingestion_assets_content_sha256'), table_name='ingestion_assets')
    op.drop_table('ingestion_assets')
    op.drop_index(op.f('ix_evidence_claims_tenant_id'), table_name='evidence_claims')
    op.drop_index(op.f('ix_evidence_claims_subject_id'), table_name='evidence_claims')
    op.drop_index(op.f('ix_evidence_claims_source_document_id'), table_name='evidence_claims')
    op.drop_index(op.f('ix_evidence_claims_review_status'), table_name='evidence_claims')
    op.drop_index(op.f('ix_evidence_claims_predicate'), table_name='evidence_claims')
    op.drop_index(op.f('ix_evidence_claims_object_id'), table_name='evidence_claims')
    op.drop_index('ix_claims_entity_predicate', table_name='evidence_claims')
    op.drop_table('evidence_claims')
    op.drop_index(op.f('ix_entity_aliases_tenant_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_normalized_alias'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index('ix_program_target_phase', table_name='development_programs')
    op.drop_index(op.f('ix_development_programs_tenant_id'), table_name='development_programs')
    op.drop_index(op.f('ix_development_programs_target_entity_id'), table_name='development_programs')
    op.drop_index(op.f('ix_development_programs_status_date'), table_name='development_programs')
    op.drop_index(op.f('ix_development_programs_phase'), table_name='development_programs')
    op.drop_index(op.f('ix_development_programs_organization_entity_id'), table_name='development_programs')
    op.drop_index(op.f('ix_development_programs_modality'), table_name='development_programs')
    op.drop_index(op.f('ix_development_programs_geography'), table_name='development_programs')
    op.drop_index(op.f('ix_development_programs_drug_entity_id'), table_name='development_programs')
    op.drop_index(op.f('ix_development_programs_disease_entity_id'), table_name='development_programs')
    op.drop_table('development_programs')
    op.drop_index(op.f('ix_deal_profiles_tenant_id'), table_name='deal_profiles')
    op.drop_index(op.f('ix_deal_profiles_entity_id'), table_name='deal_profiles')
    op.drop_index(op.f('ix_deal_profiles_deal_type'), table_name='deal_profiles')
    op.drop_index(op.f('ix_deal_profiles_announced_at'), table_name='deal_profiles')
    op.drop_table('deal_profiles')
    op.drop_index(op.f('ix_compound_structures_tenant_id'), table_name='compound_structures')
    op.drop_index(op.f('ix_compound_structures_standard_inchi_key'), table_name='compound_structures')
    op.drop_index(op.f('ix_compound_structures_entity_id'), table_name='compound_structures')
    op.drop_index('ix_compound_structure_entity', table_name='compound_structures')
    op.drop_table('compound_structures')
    op.drop_index(op.f('ix_clinical_trial_profiles_tenant_id'), table_name='clinical_trial_profiles')
    op.drop_index(op.f('ix_clinical_trial_profiles_study_type'), table_name='clinical_trial_profiles')
    op.drop_index(op.f('ix_clinical_trial_profiles_registry_id'), table_name='clinical_trial_profiles')
    op.drop_index(op.f('ix_clinical_trial_profiles_registry'), table_name='clinical_trial_profiles')
    op.drop_index(op.f('ix_clinical_trial_profiles_overall_status'), table_name='clinical_trial_profiles')
    op.drop_index(op.f('ix_clinical_trial_profiles_last_update_posted'), table_name='clinical_trial_profiles')
    op.drop_index(op.f('ix_clinical_trial_profiles_entity_id'), table_name='clinical_trial_profiles')
    op.drop_table('clinical_trial_profiles')
    op.drop_index(op.f('ix_assays_tenant_id'), table_name='assays')
    op.drop_index(op.f('ix_assays_target_entity_id'), table_name='assays')
    op.drop_index(op.f('ix_assays_source_system'), table_name='assays')
    op.drop_index(op.f('ix_assays_source_assay_id'), table_name='assays')
    op.drop_index(op.f('ix_assays_assay_type'), table_name='assays')
    op.drop_index(op.f('ix_assays_assay_format'), table_name='assays')
    op.drop_table('assays')
    op.drop_index(op.f('ix_source_documents_tenant_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_source_type'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_ragflow_document_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_ragflow_dataset_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_content_sha256'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index('ix_entities_tenant_type_name', table_name='entities')
    op.drop_index(op.f('ix_entities_tenant_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_review_status'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('tenants')
    # ### end Alembic commands ###
