import type { TrialSavedSearchInput } from "../../lib/contracts/trials";
import type { TrialFilterConditions } from "./useTrialFilterDraft";
export const emptyTrialFilterConditions: TrialFilterConditions = {
  query: "",
  registry: "",
  status: "",
  phase: "",
  studyType: "",
  acronym: "",
  initiationType: "",
  therapyLine: "",
  hasResults: "",
  resultEvaluation: "",
  resultsPostedFrom: "",
  resultsPostedTo: "",
  investigationalDrug: "",
  combinationDrug: "",
  investigationalTarget: "",
  combinationTarget: "",
  investigationalDrugEntityIds: [],
  combinationDrugEntityIds: [],
  investigationalTargetEntityIds: [],
  combinationTargetEntityIds: [],
  linkedDrugModalities: [],
  linkedDrugInnovationTypes: [],
  linkedDrugCategories: [],
  linkedDrugProgramTags: [],
  linkedDrugGlobalPhase: "",
  linkedDrugOrganizationCountryRegion: "",
  roleEntityId: "",
  roleEntityIds: [],
  roleEntityRole: "",
  hasKeyResult: "",
  publicationId: "",
  conference: "",
  disclosedFrom: "",
  disclosedTo: "",
};
export const emptyTrialSearchInput: TrialSavedSearchInput = {
  ...emptyTrialFilterConditions,
  sortBy: "last_update_posted",
  sortDirection: "desc",
  displayMode: "list",
  analysisView: "chart",
};
