import type { SortCriterion } from "../../lib/contracts/sorting";
import type { SortDirection, TrialSavedSearchInput, TrialSortField } from "../../lib/contracts/trials";
import type { EntityType } from "../../lib/generated";
import type { TrialDossierSection } from "../../lib/workspaceRouting";
export type TrialEntityOpener = (type: EntityType, id: string) => void;
export type TrialSearchChange = TrialSavedSearchInput & { offset: number };
export interface TrialsViewProps {
  displayMode: "list" | "landscape";
  analysisView: "chart" | "table";
  initialQuery: string;
  initialRegistry: string;
  initialStatus: string;
  initialPhase: string;
  initialStudyType: string;
  initialAcronym: string;
  initialInitiationType: string;
  initialTherapyLine: string;
  initialHasResults: string;
  initialResultEvaluation: string;
  initialResultsPostedFrom: string;
  initialResultsPostedTo: string;
  initialInvestigationalDrug: string;
  initialCombinationDrug: string;
  initialInvestigationalTarget: string;
  initialCombinationTarget: string;
  initialInvestigationalDrugEntityIds: string[];
  initialCombinationDrugEntityIds: string[];
  initialInvestigationalTargetEntityIds: string[];
  initialCombinationTargetEntityIds: string[];
  initialLinkedDrugModalities: string[];
  initialLinkedDrugInnovationTypes: string[];
  initialLinkedDrugCategories: string[];
  initialLinkedDrugProgramTags: string[];
  initialLinkedDrugGlobalPhase: string;
  initialLinkedDrugOrganizationCountryRegion: string;
  initialRoleEntityId: string;
  initialRoleEntityIds: string[];
  initialRoleEntityRole: string;
  initialHasKeyResult: string;
  initialPublicationId: string;
  initialConference: string;
  initialDisclosedFrom: string;
  initialDisclosedTo: string;
  initialSortBy: TrialSortField;
  initialSortDirection: SortDirection;
  initialSort?: SortCriterion<TrialSortField>[];
  initialOffset: number;
  selectedTrialId: string | null;
  activeSection: TrialDossierSection;
  onSearchChange: (change: TrialSearchChange) => void;
  onTrialChange: (trialId: string | null) => void;
  onSectionChange: (section: TrialDossierSection, replace?: boolean) => void;
  onOpenEntity: (entityId: string) => void;
  onOpenDrug?: (entityId: string) => void;
  onOpenTarget?: (entityId: string) => void;
  onOpenDisease?: (entityId: string) => void;
  onOpenOrganization?: (entityId: string) => void;
  onDisplayModeChange: (mode: "list" | "landscape") => void;
  onAnalysisViewChange: (view: "chart" | "table") => void;
  showListReturn?: boolean;
}
