export const appliedFilterLabels = {
  q: "关键词",
  registry: "注册平台",
  status: "招募状态",
  phase: "临床分期",
  study_type: "研究类型",
  acronym: "试验简称",
  initiation_type: "发起类型",
  therapy_line: "治疗线次",
  has_results: "结果发布",
  result_evaluation: "结果最优评价",
  results_posted_from: "结果发布日期",
  results_posted_to: "结果发布日期",
  investigational_drug: "试验药物",
  combination_drug: "联用药物",
  investigational_target: "试验靶点",
  combination_target: "联用靶点",
  investigational_drug_entity_ids: "试验药物（任一）",
  combination_drug_entity_ids: "联用药物（任一）",
  investigational_target_entity_ids: "试验靶点（任一）",
  combination_target_entity_ids: "联用靶点（任一）",
  linked_drug_modality: "关联药物 Modality",
  linked_drug_innovation_type: "关联药物创新类型",
  linked_drug_category: "关联药物类别",
  linked_drug_program_tag: "关联药物标签",
  linked_drug_global_phase: "关联药物全球阶段",
  linked_drug_organization_country_region: "关联药物研发机构国家/地区",
  role_entity_id: "关联药物",
  role_entity_ids: "关联药物（任一）",
  role_entity_role: "药物角色",
  has_key_result: "关键结果",
  publication_id: "发表编号",
  conference: "会议",
  disclosed_from: "披露日期",
  disclosed_to: "披露日期",
} as const;

export const trialRoleLabels: Record<string, string> = {
  investigational_drug: "试验药物",
  combination_drug: "联用药物",
  investigational_target: "试验靶点",
  combination_target: "联用靶点",
};

export const disclosureTypeLabels: Record<string, string> = {
  journal_article: "期刊论文",
  conference_abstract: "会议摘要",
  conference_presentation: "会议报告",
  registry_result: "注册结果",
  press_release: "新闻稿",
  poster: "Poster",
  other: "其他披露",
};
